if (typeof C8O === "undefined") {
  var C8O = {};
}

C8O.crudSpec = C8O.crudSpec || {};

(function () {
  function driverProfiles() {
    return {
      hsqldb: {
        id: "hsqldb",
        technology: "HSQLDB",
        jdbcDriverClassName: "org.hsqldb.jdbcDriver",
        defaultPort: 9001,
        urlBuilder: function (databaseSpec) {
          return "jdbc:hsqldb:file:./database/" + databaseSpec.database + ";shutdown=true";
        },
        identityColumn: "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "BOOLEAN",
        textType: "LONGVARCHAR"
      },
      postgresql: {
        id: "postgresql",
        technology: "PostgreSQL",
        jdbcDriverClassName: "org.postgresql.Driver",
        defaultPort: 5432,
        urlBuilder: function (databaseSpec) {
          return "jdbc:postgresql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "SERIAL PRIMARY KEY",
        autoIncrementKeyword: "SERIAL",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      mariadb: {
        id: "mariadb",
        technology: "MariaDB",
        jdbcDriverClassName: "org.mariadb.jdbc.Driver",
        defaultPort: 3306,
        urlBuilder: function (databaseSpec) {
          return "jdbc:mariadb://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT AUTO_INCREMENT PRIMARY KEY",
        autoIncrementKeyword: "AUTO_INCREMENT",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      mysql: {
        id: "mysql",
        technology: "MySQL",
        jdbcDriverClassName: "com.mysql.jdbc.Driver",
        defaultPort: 3306,
        urlBuilder: function (databaseSpec) {
          return "jdbc:mysql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT AUTO_INCREMENT PRIMARY KEY",
        autoIncrementKeyword: "AUTO_INCREMENT",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      sqlserver: {
        id: "sqlserver",
        technology: "SQLServer",
        jdbcDriverClassName: "net.sourceforge.jtds.jdbc.Driver",
        defaultPort: 1433,
        urlBuilder: function (databaseSpec) {
          return "jdbc:jtds:sqlserver://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT IDENTITY(1,1) PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "BIT",
        textType: "VARCHAR(MAX)"
      },
      oracle: {
        id: "oracle",
        technology: "Oracle",
        jdbcDriverClassName: "oracle.jdbc.driver.OracleDriver",
        defaultPort: 1521,
        urlBuilder: function (databaseSpec) {
          return "jdbc:oracle:thin:@//" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "NUMBER(1)",
        textType: "CLOB"
      }
    };
  }

  C8O.crudSpec.normalizeDriver = function (ctx, databaseSpec) {
    var rawMode = ctx.trimmed(databaseSpec.mode || databaseSpec.technology).toLowerCase();
    if (rawMode === "postgres" || rawMode === "postgresql") {
      rawMode = "postgresql";
    } else if (rawMode === "maria" || rawMode === "mariadb") {
      rawMode = "mariadb";
    } else if (rawMode === "mssql" || rawMode === "sqlserver") {
      rawMode = "sqlserver";
    } else if (rawMode === "oracle") {
      rawMode = "oracle";
    } else if (rawMode === "mysql") {
      rawMode = "mysql";
    } else if (rawMode === "hsql" || rawMode === "hsqldb") {
      rawMode = "hsqldb";
    }
    var profile = driverProfiles()[rawMode];
    if (!profile) {
      throw new Error("Unsupported database mode/technology: " + rawMode);
    }
    return ctx.clone(profile);
  };

  C8O.crudSpec.inferDriverFamilyFromConnector = function (ctx, connector) {
    var jdbcClass = "";
    try {
      jdbcClass = ctx.trimmed(connector && connector.getJdbcDriverClassName ? connector.getJdbcDriverClassName() : "");
    } catch (_ignoreJdbcClass) {
      jdbcClass = "";
    }
    if (!jdbcClass.length) {
      return "";
    }
    if (jdbcClass.indexOf("postgresql") !== -1) {
      return "postgresql";
    }
    if (jdbcClass.indexOf("mariadb") !== -1) {
      return "mariadb";
    }
    if (jdbcClass.indexOf("mysql") !== -1) {
      return "mysql";
    }
    if (jdbcClass.indexOf("jtds") !== -1 || jdbcClass.indexOf("sqlserver") !== -1) {
      return "sqlserver";
    }
    if (jdbcClass.indexOf("oracle") !== -1) {
      return "oracle";
    }
    if (jdbcClass.indexOf("hsqldb") !== -1) {
      return "hsqldb";
    }
    return jdbcClass;
  };

  C8O.crudSpec.normalizeDatabaseSpec = function (ctx, spec) {
    var raw = spec.database || {};
    var driver = C8O.crudSpec.normalizeDriver(ctx, raw);
    return {
      mode: driver.id,
      technology: driver.technology,
      connector: ctx.trimmed(raw.connector || spec.project + "db") || "appdb",
      host: ctx.trimmed(raw.host || "localhost"),
      port: raw.port != null && String(raw.port).length ? String(raw.port) : String(driver.defaultPort),
      database: ctx.trimmed(raw.database || ctx.normalizedIdentifier(spec.project)),
      user: ctx.trimmed(raw.user || (driver.id === "postgresql" ? "postgres" : (driver.id === "oracle" ? "system" : "root"))),
      password: raw.password == null ? "" : String(raw.password),
      driver: driver
    };
  };

  C8O.crudSpec.normalizeField = function (ctx, field, entityName, index) {
    var rawField = field || {};
    var rawName = ctx.trimmed(rawField.name || rawField.column || "");
    if (!rawName.length) {
      throw new Error("Field #" + index + " for entity " + entityName + " is missing name");
    }
    return {
      name: rawName,
      column: ctx.normalizedIdentifier(rawField.column || rawName),
      type: ctx.trimmed(rawField.type || "VARCHAR(255)"),
      label: ctx.trimmed(rawField.label || rawName),
      primary: ctx.toBoolean(rawField.primary, false),
      unique: ctx.toBoolean(rawField.unique, false),
      required: rawField.required == null ? false : ctx.toBoolean(rawField.required, false),
      references: rawField.references && typeof rawField.references === "object" ? ctx.clone(rawField.references) : null
    };
  };

  C8O.crudSpec.normalizeEntity = function (ctx, rawEntity) {
    if (!rawEntity || typeof rawEntity !== "object") {
      throw new Error("Each entity must be an object");
    }
    var naming = ctx.normalizeEntityNames(rawEntity, "");
    if (!naming.name.length) {
      throw new Error("Entity name is required");
    }
    var normalized = {
      name: naming.name,
      singular: naming.singular,
      label: naming.displayLabel,
      displayLabel: naming.displayLabel,
      routeSegment: naming.routeSegment,
      fields: [],
      primaryField: null
    };
    var rawFields = ctx.ensureArray(rawEntity.fields);
    for (var i = 0; i < rawFields.length; i++) {
      var field = C8O.crudSpec.normalizeField(ctx, rawFields[i], naming.name, i + 1);
      normalized.fields.push(field);
      if (field.primary && normalized.primaryField == null) {
        normalized.primaryField = field;
      }
    }
    if (normalized.primaryField == null) {
      normalized.primaryField = {
        name: "Id",
        column: "id",
        type: "INT",
        label: "Id",
        primary: true,
        unique: true,
        required: true,
        references: null
      };
      normalized.fields.unshift(normalized.primaryField);
    }
    return normalized;
  };

  C8O.crudSpec.findEntityByName = function (ctx, entities, entityName) {
    var expected = ctx.pluralize(ctx.normalizedIdentifier(entityName || ""));
    var entries = ctx.ensureArray(entities);
    for (var i = 0; i < entries.length; i++) {
      if (entries[i] && entries[i].name === expected) {
        return entries[i];
      }
    }
    return null;
  };

  C8O.crudSpec.findField = function (ctx, entity, predicate) {
    var fields = ctx.ensureArray(entity && entity.fields);
    for (var i = 0; i < fields.length; i++) {
      if (predicate(fields[i], i)) {
        return fields[i];
      }
    }
    return null;
  };

  C8O.crudSpec.applyCrmDefaults = function (ctx, spec) {
    var contacts = C8O.crudSpec.findEntityByName(ctx, spec.entities, "contacts");
    var companies = C8O.crudSpec.findEntityByName(ctx, spec.entities, "companies");
    var isCrm = !!(contacts && companies);
    if (!spec.seed.profile.length) {
      spec.seed.profile = isCrm ? "crm" : "realistic";
    }
    if (!isCrm) {
      return spec;
    }

    var companyRelationField = C8O.crudSpec.findField(ctx, contacts, function (field) {
      var column = ctx.normalizedIdentifier(field && field.column);
      return column === "company_id" || column === "companyid" || ctx.normalizedIdentifier(field && field.name) === "companyid";
    });
    if (!companyRelationField) {
      companyRelationField = {
        name: "CompanyId",
        column: "company_id",
        type: "INT",
        label: "Company",
        primary: false,
        unique: false,
        required: true,
        references: {
          entity: companies.name,
          field: companies.primaryField ? companies.primaryField.column : "id"
        }
      };
      contacts.fields.push(companyRelationField);
    } else if (!companyRelationField.references) {
      companyRelationField.references = {
        entity: companies.name,
        field: companies.primaryField ? companies.primaryField.column : "id"
      };
      if (companyRelationField.required == null) {
        companyRelationField.required = true;
      }
    }

    if (ctx.trimmed(spec.ui.variant).toLowerCase() === "dashboard" || ctx.trimmed(spec.ui.variant).toLowerCase() === "entity-pages" || !ctx.trimmed(spec.ui.variant).length) {
      spec.ui.variant = "master-detail";
    }
    return spec;
  };

  C8O.crudSpec.crmRelationContext = function (ctx, spec) {
    var contacts = C8O.crudSpec.findEntityByName(ctx, spec && spec.entities, "contacts");
    var companies = C8O.crudSpec.findEntityByName(ctx, spec && spec.entities, "companies");
    if (!contacts || !companies) {
      return null;
    }
    var relationField = C8O.crudSpec.findField(ctx, contacts, function (field) {
      return field && field.references && ctx.pluralize(ctx.normalizedIdentifier(field.references.entity)) === companies.name;
    });
    if (!relationField) {
      relationField = C8O.crudSpec.findField(ctx, contacts, function (field) {
        var column = ctx.normalizedIdentifier(field && field.column);
        return column === "company_id" || column === "companyid";
      });
      if (relationField && !relationField.references) {
        relationField.references = {
          entity: companies.name,
          field: companies.primaryField ? companies.primaryField.column : "id"
        };
      }
    }
    if (!relationField) {
      return null;
    }
    return {
      contacts: contacts,
      companies: companies,
      relationField: relationField
    };
  };

  C8O.crudSpec.normalizeSpec = function (ctx, specInput) {
    var spec = C8O.util.parseObjectInput(specInput, {
      label: "spec",
      allowEmpty: false
    });
    var result = {
      project: ctx.trimmed(spec.project),
      starter: ctx.trimmed(spec.starter || "ngx").toLowerCase(),
      facade: spec.facade && typeof spec.facade === "object" ? ctx.clone(spec.facade) : {},
      seed: spec.seed && typeof spec.seed === "object" ? ctx.clone(spec.seed) : {},
      ui: spec.ui && typeof spec.ui === "object" ? ctx.clone(spec.ui) : {},
      entities: []
    };
    if (!result.project.length) {
      throw new Error("spec.project is required");
    }
    result.database = C8O.crudSpec.normalizeDatabaseSpec(ctx, spec);
    var rawEntities = ctx.ensureArray(spec.entities);
    if (!rawEntities.length) {
      throw new Error("spec.entities must contain at least one entity");
    }
    for (var i = 0; i < rawEntities.length; i++) {
      result.entities.push(C8O.crudSpec.normalizeEntity(ctx, rawEntities[i]));
    }
    result.facade.prefix = ctx.trimmed(result.facade.prefix || "crud");
    result.facade.publicListSequence = ctx.trimmed(result.facade.publicListSequence || "");
    result.seed.enabled = result.seed.enabled == null ? true : ctx.toBoolean(result.seed.enabled, true);
    result.seed.profile = ctx.trimmed(result.seed.profile || "");
    result.seed.rowsPerEntity = parseInt(result.seed.rowsPerEntity, 10);
    result.ui.entryPage = ctx.trimmed(result.ui.entryPage || "Page");
    result.ui.variant = ctx.trimmed(result.ui.variant || "entity-pages");
    C8O.crudSpec.applyCrmDefaults(ctx, result);
    if (isNaN(result.seed.rowsPerEntity) || result.seed.rowsPerEntity <= 0) {
      result.seed.rowsPerEntity = result.seed.profile === "crm" ? 20 : 2;
    }
    return result;
  };
})();
