if (typeof C8O === "undefined") {
  var C8O = {};
}

C8O.crudSpec = C8O.crudSpec || {};

(function () {
  function driverProfiles() {
    return {
      hsqldb: {
        id: "hsqldb",
        technology: "HSQLDB",
        jdbcDriverClassName: "org.hsqldb.jdbcDriver",
        defaultPort: 9001,
        urlBuilder: function (databaseSpec) {
          return "jdbc:hsqldb:file:./database/" + databaseSpec.database + ";shutdown=true";
        },
        identityColumn: "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "BOOLEAN",
        textType: "LONGVARCHAR"
      },
      postgresql: {
        id: "postgresql",
        technology: "PostgreSQL",
        jdbcDriverClassName: "org.postgresql.Driver",
        defaultPort: 5432,
        urlBuilder: function (databaseSpec) {
          return "jdbc:postgresql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "SERIAL PRIMARY KEY",
        autoIncrementKeyword: "SERIAL",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      mariadb: {
        id: "mariadb",
        technology: "MariaDB",
        jdbcDriverClassName: "org.mariadb.jdbc.Driver",
        defaultPort: 3306,
        urlBuilder: function (databaseSpec) {
          return "jdbc:mariadb://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT AUTO_INCREMENT PRIMARY KEY",
        autoIncrementKeyword: "AUTO_INCREMENT",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      mysql: {
        id: "mysql",
        technology: "MySQL",
        jdbcDriverClassName: "com.mysql.jdbc.Driver",
        defaultPort: 3306,
        urlBuilder: function (databaseSpec) {
          return "jdbc:mysql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT AUTO_INCREMENT PRIMARY KEY",
        autoIncrementKeyword: "AUTO_INCREMENT",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      sqlserver: {
        id: "sqlserver",
        technology: "SQLServer",
        jdbcDriverClassName: "net.sourceforge.jtds.jdbc.Driver",
        defaultPort: 1433,
        urlBuilder: function (databaseSpec) {
          return "jdbc:jtds:sqlserver://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT IDENTITY(1,1) PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "BIT",
        textType: "VARCHAR(MAX)"
      },
      oracle: {
        id: "oracle",
        technology: "Oracle",
        jdbcDriverClassName: "oracle.jdbc.driver.OracleDriver",
        defaultPort: 1521,
        urlBuilder: function (databaseSpec) {
          return "jdbc:oracle:thin:@//" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "NUMBER(1)",
        textType: "CLOB"
      }
    };
  }

  C8O.crudSpec.normalizeDriver = function (ctx, databaseSpec) {
    var rawMode = ctx.trimmed(databaseSpec.mode || databaseSpec.technology).toLowerCase();
    if (rawMode === "postgres" || rawMode === "postgresql") {
      rawMode = "postgresql";
    } else if (rawMode === "maria" || rawMode === "mariadb") {
      rawMode = "mariadb";
    } else if (rawMode === "mssql" || rawMode === "sqlserver") {
      rawMode = "sqlserver";
    } else if (rawMode === "oracle") {
      rawMode = "oracle";
    } else if (rawMode === "mysql") {
      rawMode = "mysql";
    } else if (rawMode === "hsql" || rawMode === "hsqldb") {
      rawMode = "hsqldb";
    }
    var profile = driverProfiles()[rawMode];
    if (!profile) {
      throw new Error("Unsupported database mode/technology: " + rawMode);
    }
    return ctx.clone(profile);
  };

  C8O.crudSpec.inferDriverFamilyFromConnector = function (ctx, connector) {
    var jdbcClass = "";
    try {
      jdbcClass = ctx.trimmed(connector && connector.getJdbcDriverClassName ? connector.getJdbcDriverClassName() : "");
    } catch (_ignoreJdbcClass) {
      jdbcClass = "";
    }
    if (!jdbcClass.length) {
      return "";
    }
    if (jdbcClass.indexOf("postgresql") !== -1) {
      return "postgresql";
    }
    if (jdbcClass.indexOf("mariadb") !== -1) {
      return "mariadb";
    }
    if (jdbcClass.indexOf("mysql") !== -1) {
      return "mysql";
    }
    if (jdbcClass.indexOf("jtds") !== -1 || jdbcClass.indexOf("sqlserver") !== -1) {
      return "sqlserver";
    }
    if (jdbcClass.indexOf("oracle") !== -1) {
      return "oracle";
    }
    if (jdbcClass.indexOf("hsqldb") !== -1) {
      return "hsqldb";
    }
    return jdbcClass;
  };

  C8O.crudSpec.normalizeDatabaseSpec = function (ctx, spec) {
    var raw = spec.database || {};
    var driver = C8O.crudSpec.normalizeDriver(ctx, raw);
    return {
      mode: driver.id,
      technology: driver.technology,
      connector: ctx.trimmed(raw.connector || spec.project + "db") || "appdb",
      host: ctx.trimmed(raw.host || "localhost"),
      port: raw.port != null && String(raw.port).length ? String(raw.port) : String(driver.defaultPort),
      database: ctx.trimmed(raw.database || ctx.normalizedIdentifier(spec.project)),
      user: ctx.trimmed(raw.user || (driver.id === "postgresql" ? "postgres" : (driver.id === "oracle" ? "system" : "root"))),
      password: raw.password == null ? "" : String(raw.password),
      driver: driver
    };
  };

  C8O.crudSpec.normalizeField = function (ctx, field, entityName, index) {
    var rawField = field || {};
    var rawName = ctx.trimmed(rawField.name || rawField.column || "");
    if (!rawName.length) {
      throw new Error("Field #" + index + " for entity " + entityName + " is missing name");
    }
    return {
      name: rawName,
      column: ctx.normalizedIdentifier(rawField.column || rawName),
      type: ctx.trimmed(rawField.type || "VARCHAR(255)"),
      label: ctx.trimmed(rawField.label || rawName),
      primary: ctx.toBoolean(rawField.primary, false),
      unique: ctx.toBoolean(rawField.unique, false),
      required: rawField.required == null ? false : ctx.toBoolean(rawField.required, false),
      references: rawField.references && typeof rawField.references === "object" ? ctx.clone(rawField.references) : null
    };
  };

  function normalizedLookupKeys(ctx, value) {
    var primary = ctx.normalizedIdentifier(value || "");
    if (!primary.length) {
      return [];
    }
    var keys = [primary];
    var compact = primary.replace(/_/g, "");
    if (compact.length && compact !== primary) {
      keys.push(compact);
    }
    return keys;
  }

  C8O.crudSpec.normalizeEntityUi = function (ctx, rawUi) {
    var source = rawUi && typeof rawUi === "object" ? rawUi : {};

    function normalizeFieldRefs(value) {
      var entries = ctx.ensureArray(value);
      var seen = {};
      var normalized = [];
      for (var i = 0; i < entries.length; i++) {
        var token = ctx.normalizedIdentifier(entries[i]);
        if (!token.length || seen[token]) {
          continue;
        }
        seen[token] = true;
        normalized.push(token);
      }
      return normalized;
    }

    var fieldLabels = {};
    var rawFieldLabels = source.fieldLabels && typeof source.fieldLabels === "object" ? source.fieldLabels : {};
    var rawFieldLabelKeys = Object.keys(rawFieldLabels);
    for (var index = 0; index < rawFieldLabelKeys.length; index++) {
      var rawKeys = normalizedLookupKeys(ctx, rawFieldLabelKeys[index]);
      var rawValue = ctx.trimmed(rawFieldLabels[rawFieldLabelKeys[index]]);
      if (!rawKeys.length || !rawValue.length) {
        continue;
      }
      for (var rawKeyIndex = 0; rawKeyIndex < rawKeys.length; rawKeyIndex++) {
        fieldLabels[rawKeys[rawKeyIndex]] = rawValue;
      }
    }

    var relationFields = {};
    var rawRelationFields = source.relationFields && typeof source.relationFields === "object" ? source.relationFields : {};
    var relationFieldKeys = Object.keys(rawRelationFields);
    for (var relationIndex = 0; relationIndex < relationFieldKeys.length; relationIndex++) {
      var relationKeys = normalizedLookupKeys(ctx, relationFieldKeys[relationIndex]);
      if (!relationKeys.length) {
        continue;
      }
      var rawRelation = rawRelationFields[relationFieldKeys[relationIndex]];
      if (!rawRelation || typeof rawRelation !== "object") {
        continue;
      }
      var control = ctx.trimmed(rawRelation.control || "").toLowerCase();
      if (control !== "autocomplete" && control !== "select") {
        control = "";
      }
      var optionLabelField = ctx.normalizedIdentifier(rawRelation.optionLabelField || "");
      var optionValueField = ctx.normalizedIdentifier(rawRelation.optionValueField || "");
      var placeholder = ctx.trimmed(rawRelation.placeholder || "");
      for (var relationKeyIndex = 0; relationKeyIndex < relationKeys.length; relationKeyIndex++) {
        relationFields[relationKeys[relationKeyIndex]] = {
          control: control,
          optionLabelField: optionLabelField,
          optionValueField: optionValueField,
          placeholder: placeholder
        };
      }
    }

    return {
      listFields: normalizeFieldRefs(source.listFields),
      detailFields: normalizeFieldRefs(source.detailFields),
      formFields: normalizeFieldRefs(source.formFields),
      fieldLabels: fieldLabels,
      actionLabel: ctx.trimmed(source.actionLabel || ""),
      relationFields: relationFields
    };
  };

  C8O.crudSpec.normalizeEntity = function (ctx, rawEntity) {
    if (!rawEntity || typeof rawEntity !== "object") {
      throw new Error("Each entity must be an object");
    }
    var naming = ctx.normalizeEntityNames(rawEntity, "");
    if (!naming.name.length) {
      throw new Error("Entity name is required");
    }
    var normalized = {
      name: naming.name,
      singular: naming.singular,
      label: naming.displayLabel,
      displayLabel: naming.displayLabel,
      routeSegment: naming.routeSegment,
      ui: C8O.crudSpec.normalizeEntityUi(ctx, rawEntity.ui),
      fields: [],
      primaryField: null
    };
    var rawFields = ctx.ensureArray(rawEntity.fields);
    for (var i = 0; i < rawFields.length; i++) {
      var field = C8O.crudSpec.normalizeField(ctx, rawFields[i], naming.name, i + 1);
      normalized.fields.push(field);
      if (field.primary && normalized.primaryField == null) {
        normalized.primaryField = field;
      }
    }
    if (normalized.primaryField == null) {
      normalized.primaryField = {
        name: "Id",
        column: "id",
        type: "INT",
        label: "Id",
        primary: true,
        unique: true,
        required: true,
        references: null
      };
      normalized.fields.unshift(normalized.primaryField);
    }
    return normalized;
  };

  C8O.crudSpec.findEntityByName = function (ctx, entities, entityName) {
    var expected = ctx.pluralize(ctx.normalizedIdentifier(entityName || ""));
    var entries = ctx.ensureArray(entities);
    for (var i = 0; i < entries.length; i++) {
      if (entries[i] && entries[i].name === expected) {
        return entries[i];
      }
    }
    return null;
  };

  C8O.crudSpec.findField = function (ctx, entity, predicate) {
    var fields = ctx.ensureArray(entity && entity.fields);
    for (var i = 0; i < fields.length; i++) {
      if (predicate(fields[i], i)) {
        return fields[i];
      }
    }
    return null;
  };

  function relationMapKey(ctx, fromEntityName, fromFieldName) {
    return ctx.pluralize(ctx.normalizedIdentifier(fromEntityName || "")) + "::" + ctx.normalizedIdentifier(fromFieldName || "");
  }

  function relationLabelAlias(ctx, fromFieldName) {
    var column = ctx.normalizedIdentifier(fromFieldName || "");
    return column.length ? (column + "__label") : "__label";
  }

  function normalizeFieldReference(ctx, rawReference) {
    if (!rawReference || typeof rawReference !== "object") {
      return null;
    }
    var targetEntity = ctx.pluralize(ctx.normalizedIdentifier(rawReference.entity || ""));
    if (!targetEntity.length) {
      return null;
    }
    return {
      entity: targetEntity,
      field: ctx.normalizedIdentifier(rawReference.field || "id")
    };
  }

  function entityRelationUiConfig(ctx, entity, fieldColumn) {
    var relationFields = entity && entity.ui && entity.ui.relationFields && typeof entity.ui.relationFields === "object"
      ? entity.ui.relationFields
      : {};
    var keys = normalizedLookupKeys(ctx, fieldColumn || "");
    for (var i = 0; i < keys.length; i++) {
      if (relationFields[keys[i]]) {
        return ctx.clone(relationFields[keys[i]]);
      }
    }
    return {};
  }

  function preferredRelationLabelField(ctx, entity) {
    if (!entity) {
      return null;
    }
    var preferred = [
      ["displayname", "display_name", "name", "nom", "nomcommun", "commonname", "title", "titre"],
      ["firstname", "prenom", "lastname", "surname", "nomscientifique", "scientificname"],
      ["email", "city", "ville", "industry", "secteur", "category", "categorie", "venue", "badge"]
    ];
    for (var p = 0; p < preferred.length; p++) {
      for (var i = 0; i < preferred[p].length; i++) {
        var expected = ctx.normalizedIdentifier(preferred[p][i]);
        var preferredField = C8O.crudSpec.findField(ctx, entity, function (field) {
          if (!field || field.primary === true) {
            return false;
          }
          var token = ctx.normalizedIdentifier(field.column || field.name);
          return token === expected;
        });
        if (preferredField) {
          return preferredField;
        }
      }
    }
    var uniqueField = C8O.crudSpec.findField(ctx, entity, function (field) {
      return field && !field.primary && !field.references && field.unique === true;
    });
    if (uniqueField) {
      return uniqueField;
    }
    var semanticField = C8O.crudSpec.findField(ctx, entity, function (field) {
      return field && !field.primary && !field.references;
    });
    if (semanticField) {
      return semanticField;
    }
    return entity.primaryField || null;
  }

  function normalizeRelationDefinition(ctx, spec, rawRelation) {
    if (!rawRelation || typeof rawRelation !== "object") {
      return null;
    }
    var rawType = ctx.trimmed(rawRelation.type || "many-to-one").toLowerCase();
    var source = {
      name: ctx.trimmed(rawRelation.name || ""),
      type: rawType,
      required: rawRelation.required == null ? null : ctx.toBoolean(rawRelation.required, false),
      label: ctx.trimmed(rawRelation.label || "")
    };
    if (rawType === "one-to-many") {
      source.fromEntity = ctx.pluralize(ctx.normalizedIdentifier(rawRelation.toEntity || ""));
      source.fromField = ctx.normalizedIdentifier(rawRelation.toField || "");
      source.toEntity = ctx.pluralize(ctx.normalizedIdentifier(rawRelation.fromEntity || ""));
      source.toField = ctx.normalizedIdentifier(rawRelation.fromField || "id");
      source.inputType = "one-to-many";
    } else {
      source.fromEntity = ctx.pluralize(ctx.normalizedIdentifier(rawRelation.fromEntity || ""));
      source.fromField = ctx.normalizedIdentifier(rawRelation.fromField || "");
      source.toEntity = ctx.pluralize(ctx.normalizedIdentifier(rawRelation.toEntity || ""));
      source.toField = ctx.normalizedIdentifier(rawRelation.toField || "id");
      source.inputType = "many-to-one";
      source.type = "many-to-one";
    }
    if (!source.fromEntity.length || !source.fromField.length || !source.toEntity.length || !source.toField.length) {
      throw new Error("Invalid relation definition: fromEntity/fromField/toEntity/toField are required");
    }
    var fromEntity = C8O.crudSpec.findEntityByName(ctx, spec.entities, source.fromEntity);
    var toEntity = C8O.crudSpec.findEntityByName(ctx, spec.entities, source.toEntity);
    if (!fromEntity) {
      throw new Error("Unknown relation fromEntity: " + source.fromEntity);
    }
    if (!toEntity) {
      throw new Error("Unknown relation toEntity: " + source.toEntity);
    }
    var targetField = C8O.crudSpec.findField(ctx, toEntity, function (field) {
      return ctx.normalizedIdentifier(field && (field.column || field.name)) === source.toField;
    });
    if (!targetField) {
      throw new Error("Unknown relation toField `" + source.toField + "` on entity " + toEntity.name);
    }
    if (!source.label.length) {
      source.label = ctx.trimmed(toEntity.singular || toEntity.displayLabel || toEntity.label || toEntity.name);
    }
    if (!source.name.length) {
      source.name = ctx.normalizedIdentifier(fromEntity.singular + "_" + toEntity.singular);
    }
    source.toFieldType = ctx.trimmed(targetField.type || "INT");
    return source;
  }

  function ensureRelationField(ctx, spec, relation) {
    var fromEntity = C8O.crudSpec.findEntityByName(ctx, spec.entities, relation.fromEntity);
    var toEntity = C8O.crudSpec.findEntityByName(ctx, spec.entities, relation.toEntity);
    if (!fromEntity || !toEntity) {
      return null;
    }
    var targetField = C8O.crudSpec.findField(ctx, toEntity, function (field) {
      return ctx.normalizedIdentifier(field && (field.column || field.name)) === relation.toField;
    }) || toEntity.primaryField;
    var field = C8O.crudSpec.findField(ctx, fromEntity, function (candidate) {
      return ctx.normalizedIdentifier(candidate && (candidate.column || candidate.name)) === relation.fromField;
    });
    if (!field) {
      field = {
        name: relation.fromField,
        column: relation.fromField,
        type: targetField && ctx.trimmed(targetField.type).length ? targetField.type : "INT",
        label: relation.label || relation.fromField,
        primary: false,
        unique: false,
        required: relation.required === true,
        references: null
      };
      fromEntity.fields.push(field);
    }
    field.references = {
      entity: toEntity.name,
      field: targetField ? targetField.column : relation.toField
    };
    if (relation.required != null) {
      field.required = relation.required === true;
    }
    if (!ctx.trimmed(field.label).length && ctx.trimmed(relation.label).length) {
      field.label = relation.label;
    }
    if (!fromEntity.primaryField && field.primary) {
      fromEntity.primaryField = field;
    }
    relation.fromField = field.column;
    relation.toField = targetField ? targetField.column : relation.toField;
    relation.labelAlias = relationLabelAlias(ctx, relation.fromField);
    relation.ui = relation.ui || {};
    var relationUi = entityRelationUiConfig(ctx, fromEntity, relation.fromField);
    var labelField = ctx.normalizedIdentifier(relationUi.optionLabelField || "");
    if (!labelField.length) {
      var preferred = preferredRelationLabelField(ctx, toEntity);
      labelField = ctx.normalizedIdentifier(preferred && (preferred.column || preferred.name) || relation.toField);
    }
    relation.ui.control = ctx.trimmed(relationUi.control || "").toLowerCase();
    if (relation.ui.control !== "autocomplete" && relation.ui.control !== "select") {
      relation.ui.control = "select";
    }
    relation.ui.optionLabelField = labelField || relation.toField;
    relation.ui.optionValueField = ctx.normalizedIdentifier(relationUi.optionValueField || relation.toField || "id");
    relation.ui.placeholder = ctx.trimmed(relationUi.placeholder || ("Select " + (relation.label || fromEntity.singular || "value")));
    return relation;
  }

  C8O.crudSpec.normalizeRelations = function (ctx, spec, rawRelations) {
    var entries = [];
    var explicit = ctx.ensureArray(rawRelations);
    var relationMap = {};
    var priorities = {};

    function upsertRelation(relation, priority) {
      if (!relation) {
        return;
      }
      var key = relationMapKey(ctx, relation.fromEntity, relation.fromField);
      var currentPriority = priorities.hasOwnProperty(key) ? priorities[key] : -1;
      if (priority < currentPriority) {
        return;
      }
      relationMap[key] = relation;
      priorities[key] = priority;
    }

    for (var entityIndex = 0; entityIndex < spec.entities.length; entityIndex++) {
      var entity = spec.entities[entityIndex];
      var fields = ctx.ensureArray(entity && entity.fields);
      for (var fieldIndex = 0; fieldIndex < fields.length; fieldIndex++) {
        var field = fields[fieldIndex];
        var normalizedReference = normalizeFieldReference(ctx, field && field.references);
        if (!normalizedReference) {
          continue;
        }
        upsertRelation({
          name: ctx.normalizedIdentifier(entity.singular + "_" + normalizedReference.entity),
          type: "many-to-one",
          inputType: "many-to-one",
          fromEntity: entity.name,
          fromField: field.column,
          toEntity: normalizedReference.entity,
          toField: normalizedReference.field,
          required: field.required === true,
          label: ctx.trimmed(field.label || ""),
          ui: {}
        }, 1);
      }
    }

    for (var explicitIndex = 0; explicitIndex < explicit.length; explicitIndex++) {
      upsertRelation(normalizeRelationDefinition(ctx, spec, explicit[explicitIndex]), 2);
    }

    var crm = C8O.crudSpec.findEntityByName(ctx, spec.entities, "contacts") && C8O.crudSpec.findEntityByName(ctx, spec.entities, "companies");
    if (crm) {
      upsertRelation({
        name: "contact_company",
        type: "many-to-one",
        inputType: "many-to-one",
        fromEntity: "contacts",
        fromField: "company_id",
        toEntity: "companies",
        toField: "id",
        required: true,
        label: "Company",
        ui: {}
      }, 0);
    }

    var relationKeys = Object.keys(relationMap);
    relationKeys.sort();
    for (var relationIndex = 0; relationIndex < relationKeys.length; relationIndex++) {
      var applied = ensureRelationField(ctx, spec, relationMap[relationKeys[relationIndex]]);
      if (applied) {
        entries.push(applied);
      }
    }
    return entries;
  };

  C8O.crudSpec.applyCrmDefaults = function (ctx, spec) {
    var contacts = C8O.crudSpec.findEntityByName(ctx, spec.entities, "contacts");
    var companies = C8O.crudSpec.findEntityByName(ctx, spec.entities, "companies");
    var isCrm = !!(contacts && companies);
    if (!spec.seed.profile.length) {
      spec.seed.profile = isCrm ? "crm" : "realistic";
    }
    if (!isCrm) {
      return spec;
    }
    if (ctx.trimmed(spec.ui.variant).toLowerCase() === "dashboard" || ctx.trimmed(spec.ui.variant).toLowerCase() === "entity-pages" || !ctx.trimmed(spec.ui.variant).length) {
      spec.ui.variant = "master-detail";
    }
    return spec;
  };

  C8O.crudSpec.crmRelationContext = function (ctx, spec) {
    var contacts = C8O.crudSpec.findEntityByName(ctx, spec && spec.entities, "contacts");
    var companies = C8O.crudSpec.findEntityByName(ctx, spec && spec.entities, "companies");
    if (!contacts || !companies) {
      return null;
    }
    var relationField = C8O.crudSpec.findField(ctx, contacts, function (field) {
      return field && field.references && ctx.pluralize(ctx.normalizedIdentifier(field.references.entity)) === companies.name;
    });
    if (!relationField) {
      relationField = C8O.crudSpec.findField(ctx, contacts, function (field) {
        var column = ctx.normalizedIdentifier(field && field.column);
        return column === "company_id" || column === "companyid";
      });
      if (relationField && !relationField.references) {
        relationField.references = {
          entity: companies.name,
          field: companies.primaryField ? companies.primaryField.column : "id"
        };
      }
    }
    if (!relationField) {
      return null;
    }
    return {
      contacts: contacts,
      companies: companies,
      relationField: relationField
    };
  };

  C8O.crudSpec.normalizeSpec = function (ctx, specInput) {
    var spec = C8O.util.parseObjectInput(specInput, {
      label: "spec",
      allowEmpty: false
    });
    var result = {
      project: ctx.trimmed(spec.project),
      starter: ctx.trimmed(spec.starter || "ngx").toLowerCase(),
      facade: spec.facade && typeof spec.facade === "object" ? ctx.clone(spec.facade) : {},
      seed: spec.seed && typeof spec.seed === "object" ? ctx.clone(spec.seed) : {},
      ui: spec.ui && typeof spec.ui === "object" ? ctx.clone(spec.ui) : {},
      entities: [],
      relations: []
    };
    if (!result.project.length) {
      throw new Error("spec.project is required");
    }
    result.database = C8O.crudSpec.normalizeDatabaseSpec(ctx, spec);
    var rawEntities = ctx.ensureArray(spec.entities);
    if (!rawEntities.length) {
      throw new Error("spec.entities must contain at least one entity");
    }
    for (var i = 0; i < rawEntities.length; i++) {
      result.entities.push(C8O.crudSpec.normalizeEntity(ctx, rawEntities[i]));
    }
    result.facade.prefix = ctx.trimmed(result.facade.prefix || "crud");
    result.facade.publicListSequence = ctx.trimmed(result.facade.publicListSequence || "");
    result.seed.enabled = result.seed.enabled == null ? true : ctx.toBoolean(result.seed.enabled, true);
    result.seed.profile = ctx.trimmed(result.seed.profile || "");
    result.seed.rowsPerEntity = parseInt(result.seed.rowsPerEntity, 10);
    result.ui.entryPage = ctx.trimmed(result.ui.entryPage || "Page");
    result.ui.variant = ctx.trimmed(result.ui.variant || "entity-pages");
    C8O.crudSpec.applyCrmDefaults(ctx, result);
    result.relations = C8O.crudSpec.normalizeRelations(ctx, result, spec.relations);
    if (isNaN(result.seed.rowsPerEntity) || result.seed.rowsPerEntity <= 0) {
      result.seed.rowsPerEntity = result.seed.profile === "crm" ? 20 : 2;
    }
    return result;
  };

  C8O.crudSpec.relationMapKey = relationMapKey;
  C8O.crudSpec.relationLabelAlias = relationLabelAlias;
  C8O.crudSpec.entityRelationUiConfig = entityRelationUiConfig;
  C8O.crudSpec.preferredRelationLabelField = preferredRelationLabelField;
})();
