include("js/util.js");
include("js/databaseobject.js");
include("js/databaseobject_batch.js");
include("js/marketplace.js");

if (typeof C8O === "undefined") {
  var C8O = {};
}

C8O.crud = C8O.crud || {};

(function () {
  if (C8O.crud._initialized === true) {
    return;
  }
  C8O.crud._initialized = true;

  var Engine = Packages.com.twinsoft.convertigo.engine.Engine;
  var InternalRequester = Packages.com.twinsoft.convertigo.engine.requesters.InternalRequester;
  var HashMap = Packages.java.util.HashMap;
  var SqlTransaction = Packages.com.twinsoft.convertigo.beans.transactions.SqlTransaction;
  var GenericSequence = Packages.com.twinsoft.convertigo.beans.core.GenericSequence;
  var TransactionStep = Packages.com.twinsoft.convertigo.beans.steps.TransactionStep;
  var XMLCopyStep = Packages.com.twinsoft.convertigo.beans.steps.XMLCopyStep;
  var RequestableVariable = Packages.com.twinsoft.convertigo.beans.variables.RequestableVariable;
  var StepVariable = Packages.com.twinsoft.convertigo.beans.variables.StepVariable;

  function trimmed(value) {
    return C8O.util.toTrimmedString ? C8O.util.toTrimmedString(value) : (value == null ? "" : String(value).trim());
  }

  function toBoolean(value, defaultValue) {
    if (C8O.util.toBoolean) {
      return C8O.util.toBoolean(value, defaultValue);
    }
    return value == null ? !!defaultValue : String(value).toLowerCase() === "true";
  }

  function clone(value) {
    try {
      return JSON.parse(JSON.stringify(value));
    } catch (_ignoreClone) {
      return value;
    }
  }

  function ensureArray(value) {
    if (!value) {
      return [];
    }
    if (Array.isArray(value)) {
      return value;
    }
    return [value];
  }

  function ensureWarnings(target) {
    if (!target.warnings) {
      target.warnings = [];
    }
    return target.warnings;
  }

  function addWarning(target, message) {
    ensureWarnings(target).push(String(message));
  }

  function ucfirst(value) {
    var text = trimmed(value);
    if (!text.length) {
      return "";
    }
    return text.substring(0, 1).toUpperCase() + text.substring(1);
  }

  function singularize(name) {
    var text = trimmed(name);
    if (!text.length) {
      return text;
    }
    if (/ies$/i.test(text)) {
      return text.substring(0, text.length - 3) + "y";
    }
    if (/ses$/i.test(text)) {
      return text.substring(0, text.length - 2);
    }
    if (/s$/i.test(text) && text.length > 1) {
      return text.substring(0, text.length - 1);
    }
    return text;
  }

  function pluralize(name) {
    var text = trimmed(name);
    if (!text.length) {
      return text;
    }
    if (/y$/i.test(text)) {
      return text.substring(0, text.length - 1) + "ies";
    }
    if (/s$/i.test(text)) {
      return text;
    }
    return text + "s";
  }

  function escapeSqlString(value) {
    return String(value == null ? "" : value).replace(/'/g, "''");
  }

  function normalizedIdentifier(name) {
    var text = trimmed(name).replace(/[^A-Za-z0-9_]/g, "_");
    if (!text.length) {
      return "unnamed";
    }
    if (/^[0-9]/.test(text)) {
      text = "x_" + text;
    }
    return text.toLowerCase();
  }

  function driverProfiles() {
    return {
      hsqldb: {
        id: "hsqldb",
        technology: "HSQLDB",
        jdbcDriverClassName: "org.hsqldb.jdbcDriver",
        defaultPort: 9001,
        urlBuilder: function (databaseSpec, spec) {
          return "jdbc:hsqldb:file:./database/" + normalizedIdentifier(spec.project) + ";shutdown=true";
        },
        identityColumn: "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "BOOLEAN",
        textType: "VARCHAR(1024)"
      },
      postgresql: {
        id: "postgresql",
        technology: "PostgreSQL",
        jdbcDriverClassName: "org.postgresql.Driver",
        defaultPort: 5432,
        urlBuilder: function (databaseSpec) {
          return "jdbc:postgresql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "SERIAL PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      mariadb: {
        id: "mariadb",
        technology: "MariaDB",
        jdbcDriverClassName: "org.mariadb.jdbc.Driver",
        defaultPort: 3306,
        urlBuilder: function (databaseSpec) {
          return "jdbc:mariadb://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT AUTO_INCREMENT PRIMARY KEY",
        autoIncrementKeyword: "AUTO_INCREMENT",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      mysql: {
        id: "mysql",
        technology: "MySQL",
        jdbcDriverClassName: "com.mysql.cj.jdbc.Driver",
        defaultPort: 3306,
        urlBuilder: function (databaseSpec) {
          return "jdbc:mysql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT AUTO_INCREMENT PRIMARY KEY",
        autoIncrementKeyword: "AUTO_INCREMENT",
        booleanType: "BOOLEAN",
        textType: "TEXT"
      },
      sqlserver: {
        id: "sqlserver",
        technology: "SQLServer",
        jdbcDriverClassName: "net.sourceforge.jtds.jdbc.Driver",
        defaultPort: 1433,
        urlBuilder: function (databaseSpec) {
          return "jdbc:jtds:sqlserver://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "INT IDENTITY(1,1) PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "BIT",
        textType: "VARCHAR(MAX)"
      },
      oracle: {
        id: "oracle",
        technology: "Oracle",
        jdbcDriverClassName: "oracle.jdbc.driver.OracleDriver",
        defaultPort: 1521,
        urlBuilder: function (databaseSpec) {
          return "jdbc:oracle:thin:@//" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
        },
        identityColumn: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        autoIncrementKeyword: "",
        booleanType: "NUMBER(1)",
        textType: "CLOB"
      }
    };
  }

  function normalizeDriver(databaseSpec) {
    var rawMode = trimmed(databaseSpec.mode || databaseSpec.technology).toLowerCase();
    if (rawMode === "postgres" || rawMode === "postgresql") {
      rawMode = "postgresql";
    } else if (rawMode === "maria" || rawMode === "mariadb") {
      rawMode = "mariadb";
    } else if (rawMode === "mssql" || rawMode === "sqlserver") {
      rawMode = "sqlserver";
    } else if (rawMode === "oracle") {
      rawMode = "oracle";
    } else if (rawMode === "mysql") {
      rawMode = "mysql";
    } else if (rawMode === "hsql" || rawMode === "hsqldb") {
      rawMode = "hsqldb";
    }
    var profile = driverProfiles()[rawMode];
    if (!profile) {
      throw new Error("Unsupported database mode/technology: " + rawMode);
    }
    return clone(profile);
  }

  function inferDriverFamilyFromConnector(connector) {
    var jdbcClass = "";
    try {
      jdbcClass = trimmed(connector && connector.getJdbcDriverClassName ? connector.getJdbcDriverClassName() : "");
    } catch (_ignoreJdbcClass) {
      jdbcClass = "";
    }
    if (!jdbcClass.length) {
      return "";
    }
    if (jdbcClass.indexOf("postgresql") !== -1) {
      return "postgresql";
    }
    if (jdbcClass.indexOf("mariadb") !== -1) {
      return "mariadb";
    }
    if (jdbcClass.indexOf("mysql") !== -1) {
      return "mysql";
    }
    if (jdbcClass.indexOf("jtds") !== -1 || jdbcClass.indexOf("sqlserver") !== -1) {
      return "sqlserver";
    }
    if (jdbcClass.indexOf("oracle") !== -1) {
      return "oracle";
    }
    if (jdbcClass.indexOf("hsqldb") !== -1) {
      return "hsqldb";
    }
    return jdbcClass;
  }

  function normalizeDatabaseSpec(spec, result) {
    var raw = spec.database || {};
    var driver = normalizeDriver(raw);
    return {
      mode: driver.id,
      technology: driver.technology,
      connector: trimmed(raw.connector || spec.project + "db") || "appdb",
      host: trimmed(raw.host || "localhost"),
      port: raw.port != null && String(raw.port).length ? String(raw.port) : String(driver.defaultPort),
      database: trimmed(raw.database || normalizedIdentifier(spec.project)),
      user: trimmed(raw.user || (driver.id === "postgresql" ? "postgres" : (driver.id === "oracle" ? "system" : "root"))),
      password: raw.password == null ? "" : String(raw.password),
      driver: driver
    };
  }

  function normalizeField(field, entityName, index, result) {
    var rawField = field || {};
    var rawName = trimmed(rawField.name || rawField.column || "");
    if (!rawName.length) {
      throw new Error("Field #" + index + " for entity " + entityName + " is missing name");
    }
    return {
      name: rawName,
      column: normalizedIdentifier(rawName),
      type: trimmed(rawField.type || "VARCHAR(255)"),
      label: trimmed(rawField.label || rawName),
      primary: toBoolean(rawField.primary, false),
      unique: toBoolean(rawField.unique, false),
      required: rawField.required == null ? false : toBoolean(rawField.required, false),
      references: rawField.references && typeof rawField.references === "object" ? clone(rawField.references) : null
    };
  }

  function normalizeEntity(rawEntity, result) {
    if (!rawEntity || typeof rawEntity !== "object") {
      throw new Error("Each entity must be an object");
    }
    var entityName = pluralize(normalizedIdentifier(rawEntity.name || rawEntity.entity || ""));
    if (!entityName.length) {
      throw new Error("Entity name is required");
    }
    var normalized = {
      name: entityName,
      singular: singularize(entityName),
      label: trimmed(rawEntity.label || ucfirst(entityName)),
      fields: [],
      primaryField: null
    };
    var rawFields = ensureArray(rawEntity.fields);
    for (var i = 0; i < rawFields.length; i++) {
      var field = normalizeField(rawFields[i], entityName, i + 1, result);
      normalized.fields.push(field);
      if (field.primary && normalized.primaryField == null) {
        normalized.primaryField = field;
      }
    }
    if (normalized.primaryField == null) {
      normalized.primaryField = {
        name: "Id",
        column: "id",
        type: "INT",
        label: "Id",
        primary: true,
        unique: true,
        required: true,
        references: null
      };
      normalized.fields.unshift(normalized.primaryField);
    }
    return normalized;
  }

  function normalizeSpec(specInput) {
    var spec = C8O.util.parseObjectInput(specInput, {
      label: "spec",
      allowEmpty: false
    });
    var result = {
      project: trimmed(spec.project),
      starter: trimmed(spec.starter || "ngx").toLowerCase(),
      facade: spec.facade && typeof spec.facade === "object" ? clone(spec.facade) : {},
      seed: spec.seed && typeof spec.seed === "object" ? clone(spec.seed) : {},
      ui: spec.ui && typeof spec.ui === "object" ? clone(spec.ui) : {},
      entities: []
    };
    if (!result.project.length) {
      throw new Error("spec.project is required");
    }
    result.database = normalizeDatabaseSpec(spec, result);
    var rawEntities = ensureArray(spec.entities);
    if (!rawEntities.length) {
      throw new Error("spec.entities must contain at least one entity");
    }
    for (var i = 0; i < rawEntities.length; i++) {
      result.entities.push(normalizeEntity(rawEntities[i], result));
    }
    result.facade.prefix = trimmed(result.facade.prefix || "crud");
    result.facade.publicListSequence = trimmed(result.facade.publicListSequence || "");
    result.seed.enabled = result.seed.enabled == null ? true : toBoolean(result.seed.enabled, true);
    result.seed.rowsPerEntity = parseInt(result.seed.rowsPerEntity, 10);
    if (isNaN(result.seed.rowsPerEntity) || result.seed.rowsPerEntity <= 0) {
      result.seed.rowsPerEntity = 2;
    }
    result.ui.entryPage = trimmed(result.ui.entryPage || "Page");
    result.ui.variant = trimmed(result.ui.variant || "dashboard");
    return result;
  }

	  function findProjectByName(projectName) {
	    var projectToken = trimmed(projectName);
	    if (!projectToken.length) {
	      return null;
	    }
	    try {
	      return Engine.theApp.databaseObjectsManager.getOriginalProjectByName(projectToken, false);
	    } catch (_ignoreProjectByNameWithFlag) {
	      try {
	        return Engine.theApp.databaseObjectsManager.getOriginalProjectByName(projectToken);
	      } catch (_ignoreProjectByName) {
	        try {
	          var names = C8O.dbo && C8O.dbo._listProjectNames ? C8O.dbo._listProjectNames() : [];
	          for (var i = 0; i < names.length; i++) {
	            if (String(names[i]) === projectToken) {
	              return C8O.dbo.resolve(projectToken, { optional: true });
	            }
	          }
	        } catch (_ignoreResolveProjectByQName) {}
	        return null;
	      }
	    }
	  }

  function ensureProject(spec, result) {
    var project = findProjectByName(spec.project);
    if (project) {
      return project;
    }
    if (spec.starter !== "ngx") {
      throw new Error("Project " + spec.project + " is not loaded and only starter=\"ngx\" auto-import is supported");
    }
    var importResult = C8O.marketplace.importLibrary({
      project: "template_ngxBuilderIonic",
      importedProjectName: spec.project,
      save: true,
      forceImport: false
    });
    var importReady = !!(
      importResult &&
      (
        importResult.status === "ready" ||
        importResult.status === "ok" ||
        importResult.imported === true ||
        importResult.loadedAfter === true
      )
    );
    if (!importReady) {
      var importMessage = importResult && importResult.importMessage ? String(importResult.importMessage) : "";
      throw new Error(
        "Unable to import NGX starter for project " +
        spec.project +
        (importMessage.length ? " (" + importMessage + ")" : "")
      );
    }
    result.created.push(spec.project);
    project = findProjectByName(spec.project);
    if (!project) {
      throw new Error("Imported project " + spec.project + " is still not available in memory");
    }
    return project;
  }

  function logicalClassName(node) {
    if (!node || !node.getClass) {
      return "";
    }
    try {
      return C8O.util.fromFqcn(String(node.getClass().getName() || ""));
    } catch (_ignoreLogicalClass) {
      return "";
    }
  }

  function findChild(parent, name, className) {
    if (!parent || !parent.getDatabaseObjectChildren) {
      return null;
    }
    var children = parent.getDatabaseObjectChildren();
    for (var i = 0; i < children.size(); i++) {
      var child = children.get(i);
      var matchesName = !name;
      if (!matchesName) {
        try {
          matchesName = String(child.getName()) === name;
        } catch (_ignoreChildName) {
          matchesName = false;
        }
      }
      if (!matchesName) {
        continue;
      }
      if (!className) {
        return child;
      }
      var logical = logicalClassName(child);
      if (logical === className || String(child.getClass().getName()) === C8O.util.toFqcn(className)) {
        return child;
      }
    }
    return null;
  }

  function createChild(parent, className, name) {
    var dbo = C8O.dbo.instantiateForCreate(className, parent, {});
    dbo.setName(name);
    if (typeof parent.addVariable === "function" && (className === "variables.RequestableVariable" || className === "variables.StepVariable")) {
      parent.addVariable(dbo);
    } else {
      parent.add(dbo);
    }
    try {
      dbo.hasChanged = true;
    } catch (_ignoreDboChanged) {}
    try {
      parent.hasChanged = true;
    } catch (_ignoreParentChanged) {}
    try {
      var project = parent.getProject ? parent.getProject() : null;
      if (project) {
        project.hasChanged = true;
      }
    } catch (_ignoreProjectChanged) {}
    return dbo;
  }

  function removeChild(parent, child, result) {
    if (!parent || !child) {
      return;
    }
    try {
      parent.remove(child);
      try {
        child.hasChanged = true;
      } catch (_ignoreChildChangedFlag) {}
      try {
        parent.hasChanged = true;
      } catch (_ignoreParentChangedFlag) {}
      try {
        var project = parent.getProject ? parent.getProject() : null;
        if (project) {
          project.hasChanged = true;
        }
      } catch (_ignoreProjectFlag) {}
      if (result && result.updated) {
        result.updated.push(child.getFullQName ? String(child.getFullQName()) : String(child));
      }
    } catch (removeError) {
      addWarning(result || {}, "Unable to remove child " + String(child) + ": " + String(removeError));
    }
  }

  function ensureChild(parent, className, name, result) {
    var existing = findChild(parent, name, className);
    if (existing) {
      return existing;
    }
    var created = createChild(parent, className, name);
    result.created.push(created.getFullQName ? String(created.getFullQName()) : name);
    return created;
  }

  function priorityOf(dbo) {
    try {
      if (dbo.getPriority) {
        return String(dbo.getPriority());
      }
    } catch (_ignorePriorityMethod) {}
    try {
      if (dbo.priority != null) {
        return String(dbo.priority);
      }
    } catch (_ignorePriorityField) {}
    return "";
  }

  function applyUpdates(dbo, updates, result) {
    var applied = C8O.dbo.applyPropertyUpdates(dbo, updates || {});
    if (applied && applied.errors && applied.errors.length) {
      for (var i = 0; i < applied.errors.length; i++) {
        addWarning(result, applied.errors[i].message || applied.errors[i]);
      }
    }
    if (applied && applied.applied && applied.applied.length) {
      result.updated.push(dbo.getFullQName ? String(dbo.getFullQName()) : String(dbo));
    }
    return applied;
  }

  function sameBaseClass(dbo, className) {
    if (!dbo || !className) {
      return false;
    }
    try {
      var parsed = C8O.dbo.parseLogicalClassToken(className || "");
      return String(dbo.getClass().getName()) === String(parsed.baseClassFqcn || className);
    } catch (_ignoreSameBaseClass) {
      return false;
    }
  }

  function getChildrenArray(parent) {
    var list = [];
    if (!parent || !parent.getDatabaseObjectChildren) {
      return list;
    }
    try {
      var children = parent.getDatabaseObjectChildren();
      for (var i = 0; i < children.size(); i++) {
        list.push(children.get(i));
      }
    } catch (_ignoreChildrenArray) {}
    return list;
  }

  function syncDeterministicNode(parent, spec, result, replaceChildren) {
    if (!parent || !spec) {
      return null;
    }
    var existing = findChild(parent, spec.name, null);
    if (existing && spec.className && !sameBaseClass(existing, spec.className)) {
      removeChild(parent, existing, result);
      existing = null;
    }
    var dbo = existing || createChild(parent, spec.className, spec.name);
    if (!existing && result && result.created) {
      result.created.push(dbo.getFullQName ? String(dbo.getFullQName()) : String(dbo));
    }
    if (spec.properties) {
      applyUpdates(dbo, spec.properties, result);
    }
    var desiredChildren = ensureArray(spec.children);
    var desiredByName = {};
    for (var i = 0; i < desiredChildren.length; i++) {
      if (desiredChildren[i] && desiredChildren[i].name) {
        desiredByName[String(desiredChildren[i].name)] = true;
      }
    }
    if (replaceChildren) {
      var currentChildren = getChildrenArray(dbo);
      for (var j = 0; j < currentChildren.length; j++) {
        var childName = "";
        try {
          childName = String(currentChildren[j].getName());
        } catch (_ignoreChildName) {
          childName = "";
        }
        if (childName && !desiredByName[childName]) {
          removeChild(dbo, currentChildren[j], result);
        }
      }
    }
    for (var childIndex = 0; childIndex < desiredChildren.length; childIndex++) {
      syncDeterministicNode(dbo, desiredChildren[childIndex], result, true);
    }
    return dbo;
  }

	  function connectorProperties(spec) {
	    var db = spec.database;
	    return {
	      jdbcDriverClassName: db.driver.jdbcDriverClassName,
	      jdbcURL: buildJdbcUrl(db, spec),
	      jdbcUserName: db.driver.id === "hsqldb" ? "SA" : db.user,
	      jdbcUserPassword: db.driver.id === "hsqldb" ? "" : db.password,
	      comment: "Deterministic CRUD connector (" + db.driver.technology + ") for " + spec.project
	    };
	  }

	  function buildJdbcUrl(databaseSpec, spec) {
	    var driverId = databaseSpec && databaseSpec.driver && databaseSpec.driver.id ? String(databaseSpec.driver.id) : "hsqldb";
	    if (driverId === "postgresql") {
	      return "jdbc:postgresql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
	    }
	    if (driverId === "mariadb") {
	      return "jdbc:mariadb://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
	    }
	    if (driverId === "mysql") {
	      return "jdbc:mysql://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
	    }
	    if (driverId === "sqlserver") {
	      return "jdbc:jtds:sqlserver://" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
	    }
	    if (driverId === "oracle") {
	      return "jdbc:oracle:thin:@//" + databaseSpec.host + ":" + databaseSpec.port + "/" + databaseSpec.database;
	    }
	    return "jdbc:hsqldb:file:./database/" + normalizedIdentifier(spec.project) + ";shutdown=true";
	  }

  function mapSqlType(field, driver) {
    var raw = trimmed(field.type || "").toUpperCase();
    if (!raw.length) {
      raw = "VARCHAR(255)";
    }
    if (raw === "TEXT") {
      return driver.textType;
    }
    if (raw === "BOOLEAN") {
      return driver.booleanType;
    }
    if (raw === "INT" || raw === "INTEGER") {
      return driver.id === "oracle" ? "NUMBER" : "INT";
    }
    return raw;
  }

  function renderColumnDefinition(field, driver) {
    if (field.primary) {
      if (field.column === "id") {
        return field.column + " " + driver.identityColumn;
      }
      var pkType = mapSqlType(field, driver);
      return field.column + " " + pkType + " PRIMARY KEY";
    }
    var segments = [field.column, mapSqlType(field, driver)];
    if (field.required) {
      segments.push("NOT NULL");
    }
    if (field.unique) {
      segments.push("UNIQUE");
    }
    if (field.references && field.references.entity) {
      var target = pluralize(normalizedIdentifier(field.references.entity));
      var targetColumn = normalizedIdentifier(field.references.field || "id");
      segments.push("REFERENCES " + target + "(" + targetColumn + ")");
    }
    return segments.join(" ");
  }

  function buildCreateTableSql(spec, entity) {
    var driver = spec.database.driver;
    var columnLines = [];
    for (var i = 0; i < entity.fields.length; i++) {
      columnLines.push("  " + renderColumnDefinition(entity.fields[i], driver));
    }
    var createPrefix = driver.id === "oracle" ? "CREATE TABLE " : "CREATE TABLE IF NOT EXISTS ";
    return createPrefix + entity.name + " (\n" + columnLines.join(",\n") + "\n)";
  }

  function sampleValueForField(entity, field, rowIndex) {
    var base = rowIndex + 1;
    var column = field.column;
    if (field.primary) {
      return null;
    }
    if (column.indexOf("email") !== -1) {
      return entity.singular + base + "@example.test";
    }
    if (column.indexOf("first") !== -1) {
      return ucfirst(entity.singular) + base;
    }
    if (column.indexOf("last") !== -1) {
      return "Demo" + base;
    }
    if (column.indexOf("name") !== -1) {
      return ucfirst(entity.singular) + " " + base;
    }
    if (column.indexOf("status") !== -1) {
      return rowIndex % 2 === 0 ? "active" : "lead";
    }
    if (column.indexOf("city") !== -1) {
      return rowIndex % 2 === 0 ? "Paris" : "Lyon";
    }
    if (column.indexOf("industry") !== -1) {
      return rowIndex % 2 === 0 ? "Software" : "Services";
    }
    return ucfirst(field.label || field.name) + " " + base;
  }

  function buildSeedSql(spec, entity) {
    if (spec.seed.enabled !== true) {
      return "";
    }
    var fields = [];
    for (var i = 0; i < entity.fields.length; i++) {
      if (!entity.fields[i].primary) {
        fields.push(entity.fields[i]);
      }
    }
    if (!fields.length) {
      return "";
    }
    var statements = ["DELETE FROM " + entity.name];
    var rowCount = Math.max(1, Math.min(spec.seed.rowsPerEntity, 5));
    var values = [];
    for (var row = 0; row < rowCount; row++) {
      var rowValues = [];
      for (var j = 0; j < fields.length; j++) {
        rowValues.push("'" + escapeSqlString(sampleValueForField(entity, fields[j], row)) + "'");
      }
      values.push("  (" + rowValues.join(", ") + ")");
    }
    statements.push(
      "INSERT INTO " + entity.name + " (" + fields.map(function (item) { return item.column; }).join(", ") + ") VALUES\n" + values.join(",\n")
    );
    return statements.join(";\n") + ";";
  }

  function buildInitSql(spec) {
    var chunks = [];
    for (var i = 0; i < spec.entities.length; i++) {
      chunks.push(buildCreateTableSql(spec, spec.entities[i]) + ";");
    }
    for (var j = 0; j < spec.entities.length; j++) {
      var seedSql = buildSeedSql(spec, spec.entities[j]);
      if (seedSql.length) {
        chunks.push(seedSql);
      }
    }
    return chunks.join("\n\n");
  }

  function listColumns(entity) {
    var columns = [];
    for (var i = 0; i < entity.fields.length; i++) {
      columns.push(entity.fields[i].column);
    }
    return columns;
  }

  function txName(entity, verb) {
    var plural = entity.name;
    var singular = entity.singular;
    switch (verb) {
      case "init":
        return "init_schema";
      case "seed":
        return "seed_" + plural;
      case "list":
        return "list_" + plural;
      case "count":
        return "count_" + plural;
      case "read":
        return "read_" + singular;
      case "create":
        return "create_" + singular;
      case "update":
        return "update_" + singular;
      case "delete":
        return "delete_" + singular;
      default:
        return verb + "_" + plural;
    }
  }

  function buildCrudSql(entity, verb) {
    var columns = listColumns(entity);
    var pk = entity.primaryField.column;
    var nonPkFields = entity.fields.filter(function (field) { return !field.primary; });
    if (verb === "list") {
      return "SELECT " + columns.join(", ") + "\nFROM " + entity.name + "\nORDER BY " + pk + " ASC";
    }
    if (verb === "count") {
      return "SELECT COUNT(*) AS total\nFROM " + entity.name;
    }
    if (verb === "read") {
      return "SELECT " + columns.join(", ") + "\nFROM " + entity.name + "\nWHERE " + pk + " = {" + pk + "}";
    }
    if (verb === "create") {
      return "INSERT INTO " + entity.name + " (" + nonPkFields.map(function (field) { return field.column; }).join(", ") + ")\nVALUES (" + nonPkFields.map(function (field) { return "{" + field.column + "}"; }).join(", ") + ")";
    }
    if (verb === "update") {
      return "UPDATE " + entity.name + "\nSET " + nonPkFields.map(function (field) { return field.column + " = {" + field.column + "}"; }).join(",\n    ") + "\nWHERE " + pk + " = {" + pk + "}";
    }
    if (verb === "delete") {
      return "DELETE FROM " + entity.name + "\nWHERE " + pk + " = {" + pk + "}";
    }
    return "";
  }

  function ensureConnector(project, spec, result) {
    var connector = ensureChild(project, "connectors.SqlConnector", spec.database.connector, result);
    applyUpdates(connector, connectorProperties(spec), result);
    try {
      project.setDefaultConnector(connector);
    } catch (_ignoreDefaultConnector) {}
    return connector;
  }

  function findSqlConnectorInProject(project, preferredName) {
    if (!project) {
      return null;
    }
    var preferred = trimmed(preferredName);
    if (preferred.length) {
      var byName = C8O.dbo.resolve(String(project.getName()) + "." + preferred, { optional: true });
      if (byName) {
        return byName;
      }
    }
    try {
      var defaultConnector = project.getDefaultConnector ? project.getDefaultConnector() : null;
      if (defaultConnector && String(defaultConnector.getClass().getName()).indexOf("SqlConnector") !== -1) {
        return defaultConnector;
      }
    } catch (_ignoreDefaultSqlConnector) {}
    try {
      var connectors = project.getConnectorsList();
      for (var i = 0; i < connectors.size(); i++) {
        var connector = connectors.get(i);
        if (connector && String(connector.getClass().getName()).indexOf("SqlConnector") !== -1) {
          return connector;
        }
      }
    } catch (_ignoreConnectorsList) {}
    return null;
  }

  function ensureSqlTransaction(connector, name, sqlQuery, autoCommit, result) {
    var tx = ensureChild(connector, "transactions.SqlTransaction", name, result);
    try {
      tx.setComment("Deterministic CRUD transaction " + name);
    } catch (_ignoreTxComment) {}
    tx.setSqlQuery(String(sqlQuery || ""));
    tx.setAutoCommit(autoCommit);
    tx.initializeQueries(true);
    result.updated.push(tx.getFullQName ? String(tx.getFullQName()) : name);
    return tx;
  }

  function collectTransactionVariables(tx) {
    var names = [];
    try {
      var vars = tx.getVariables();
      for (var i = 0; i < vars.size(); i++) {
        var variable = vars.get(i);
        names.push(String(variable.getName()));
      }
    } catch (_ignoreTxVariables) {}
    return names;
  }

  function ensureRequestableVariables(container, variableNames, result) {
    for (var i = 0; i < variableNames.length; i++) {
      var name = String(variableNames[i]);
      var variable = findChild(container, name, "variables.RequestableVariable");
      if (!variable) {
        variable = createChild(container, "variables.RequestableVariable", name);
        result.created.push(variable.getFullQName ? String(variable.getFullQName()) : name);
      }
      try {
        variable.setDescription("Deterministic CRUD variable " + name);
      } catch (_ignoreRequestableVariableDescription) {}
    }
  }

  function ensureStepVariables(step, variableNames, result) {
    for (var i = 0; i < variableNames.length; i++) {
      var name = String(variableNames[i]);
      var variable = findChild(step, name, "variables.StepVariable");
      if (!variable) {
        variable = createChild(step, "variables.StepVariable", name);
        result.created.push(variable.getFullQName ? String(variable.getFullQName()) : name);
      }
      try {
        variable.setDescription("Forward request variable " + name);
      } catch (_ignoreStepVariableDescription) {}
    }
  }

  function ensurePublicSequence(project, sequenceName, sourceTransaction, variableNames, result) {
    var sequence = ensureChild(project, "sequences.GenericSequence", sequenceName, result);
    try {
      sequence.setComment("Deterministic CRUD facade " + sequenceName);
    } catch (_ignoreSequenceComment) {}
    ensureRequestableVariables(sequence, variableNames, result);
    var txStep = ensureChild(sequence, "steps.TransactionStep", "Call" + ucfirst(sequenceName), result);
    txStep.setSourceTransaction(sourceTransaction);
    txStep.setOutput(true);
    ensureStepVariables(txStep, variableNames, result);
    var copyStep = ensureChild(sequence, "steps.XMLCopyStep", "CopyPayload", result);
    var sourcePriority = priorityOf(txStep);
    applyUpdates(copyStep, {
      sourceDefinition: [sourcePriority, "./document/*"]
    }, result);
    return sequence;
  }

  function callInternalSequence(sequenceName, argsMap) {
    var request = new HashMap();
    request.put("__project", "ConvertigoMCP");
    request.put("__sequence", sequenceName);
    request.put("__nolog", "true");
    var keys = Object.keys(argsMap || {});
    for (var i = 0; i < keys.length; i++) {
      var key = keys[i];
      var value = argsMap[key];
      if (value === undefined || value === null) {
        continue;
      }
      if (typeof value === "object") {
        request.put(String(key), JSON.stringify(value));
      } else {
        request.put(String(key), String(value));
      }
    }
    var requester = null;
    try {
      requester = new InternalRequester(request, context.httpServletRequest);
    } catch (_ignoreHttpRequest) {
      requester = new InternalRequester(request);
    }
    var response = requester.processRequest();
    var root = response && response.getDocumentElement ? response.getDocumentElement() : response;
    var XMLUtils = Packages.com.twinsoft.convertigo.engine.util.XMLUtils;
    var parsed = JSON.parse(String(XMLUtils.XmlToJson(root, true, true)));
    var payload = parsed && parsed.document ? parsed.document : parsed;
    return payload && payload.result !== undefined ? payload.result : payload;
  }

  function normalizeStatus(value, fallback) {
    var text = trimmed(value || fallback || "");
    return text.length ? text : (fallback || "");
  }

  function isSuccessLikeStatus(value) {
    var status = normalizeStatus(value, "ok").toLowerCase();
    return status !== "error" && status !== "failed" && status !== "not_found";
  }

  function summarizeSaveResult(saveResult, result) {
    var safe = C8O.util.toJsonSafe ? C8O.util.toJsonSafe(saveResult, {
      warnings: ensureWarnings(result),
      path: "$.runtimeEvidence.projectSave"
    }) : saveResult;
    return {
      status: normalizeStatus(safe && safe.status, "ok")
    };
  }

  function summarizeStudioRefreshResult(refreshResult, targetQName, result, path) {
    var safe = C8O.util.toJsonSafe ? C8O.util.toJsonSafe(refreshResult, {
      warnings: ensureWarnings(result),
      path: path || "$.runtimeEvidence.studioRefresh"
    }) : refreshResult;
    return {
      status: normalizeStatus(safe && safe.status, "skipped"),
      target: trimmed(safe && safe.targetQName) || trimmed(safe && safe.qname) || trimmed(targetQName),
      refreshed: safe && safe.refreshed === true,
      refreshedQName: trimmed(safe && safe.refreshedQName),
      executed: safe && safe.executed === true,
      studioMode: safe && safe.studioMode === true
    };
  }

  function refreshStudioProjectTree(project, result, evidenceKey) {
    var projectQName = "";
    try {
      projectQName = project && project.getQName ? String(project.getQName()) : "";
    } catch (_ignoreProjectQName) {
      projectQName = "";
    }
    if (!projectQName.length) {
      addWarning(result, "Unable to refresh Studio tree: project QName is unavailable");
      return {
        status: "error",
        target: "",
        refreshed: false,
        refreshedQName: "",
        executed: false,
        studioMode: false
      };
    }
    var refreshResult = C8O.dbo.refreshStudioTreeByQName(projectQName, ensureWarnings(result));
    return summarizeStudioRefreshResult(
      refreshResult,
      projectQName,
      result,
      "$.runtimeEvidence." + trimmed(evidenceKey || "studioRefresh")
    );
  }

  function collectNestedValue(payload, paths) {
    for (var i = 0; i < paths.length; i++) {
      var current = payload;
      var parts = paths[i];
      var ok = true;
      for (var j = 0; j < parts.length; j++) {
        var key = parts[j];
        if (current == null || typeof current !== "object" || !(key in current)) {
          ok = false;
          break;
        }
        current = current[key];
      }
      if (ok && current !== undefined && current !== null) {
        return current;
      }
    }
    return null;
  }

  function summarizeRequestableProof(payload, requestable, result) {
    var safe = C8O.util.toJsonSafe ? C8O.util.toJsonSafe(payload, {
      warnings: ensureWarnings(result),
      path: "$.runtimeEvidence." + normalizedIdentifier(requestable)
    }) : payload;
    var summary = {
      requestable: requestable,
      status: normalizeStatus(safe && safe.status, "ok"),
      ok: isSuccessLikeStatus(safe && safe.status)
    };

    var totalValue = collectNestedValue(safe, [
      ["total"],
      ["result", "total"],
      ["response", "total"],
      ["item", "total"],
      ["document", "total"]
    ]);
    if (totalValue != null && totalValue !== "") {
      var totalNumber = Number(totalValue);
      summary.total = isNaN(totalNumber) ? String(totalValue) : totalNumber;
    }

    var itemsValue = collectNestedValue(safe, [
      ["items"],
      ["result", "items"],
      ["response", "items"],
      ["document", "items"]
    ]);
    if (Array.isArray(itemsValue)) {
      summary.itemCount = itemsValue.length;
    }

    var sourceValue = collectNestedValue(safe, [
      ["source"],
      ["result", "source"],
      ["response", "source"],
      ["document", "source"]
    ]);
    if (sourceValue != null && sourceValue !== "") {
      summary.source = String(sourceValue);
    }

    var messageValue = collectNestedValue(safe, [
      ["message"],
      ["result", "message"],
      ["response", "message"],
      ["error"],
      ["result", "error"],
      ["response", "error"]
    ]);
    if (!summary.ok && messageValue != null && messageValue !== "") {
      summary.message = String(messageValue);
    }

    return summary;
  }

  function proofRequestable(requestable, variables, result) {
    try {
      var payload = callInternalSequence("tools_requestable_execute", {
        requestable: requestable,
        variables: variables || {}
      });
      return summarizeRequestableProof(payload, requestable, result);
    } catch (proofError) {
      addWarning(result, "Unable to execute proof for " + requestable + ": " + String(proofError));
      return {
        requestable: requestable,
        status: "error",
        ok: false,
        message: String(proofError)
      };
    }
  }

  function summarizeTreeApplyResult(treeResult, target, result) {
    var safe = C8O.util.toJsonSafe ? C8O.util.toJsonSafe(treeResult, {
      warnings: ensureWarnings(result),
      path: "$.runtimeEvidence.treeApply"
    }) : treeResult;
    return {
      status: normalizeStatus(safe && safe.status, "success"),
      target: target
    };
  }

  function applicationQName(projectName) {
    return trimmed(projectName) + ".Application";
  }

  function ngxAppQName(projectName) {
    return applicationQName(projectName) + ".NgxApp";
  }

  function findPageContentQName(projectName, entryPage) {
    return trimmed(projectName) + ".Application.NgxApp." + trimmed(entryPage || "Page") + ".Content";
  }

  function sharedComponentQName(projectName, componentName) {
    return ngxAppQName(projectName) + "." + trimmed(componentName);
  }

  function normalizeUiEntities(rawEntities) {
    var entries = ensureArray(rawEntities);
    var normalized = [];
    for (var i = 0; i < entries.length; i++) {
      var raw = entries[i] || {};
      var entityName = pluralize(normalizedIdentifier(raw.name || raw.entity || raw.label || ("entity_" + (i + 1))));
      normalized.push({
        name: entityName,
        singular: singularize(entityName),
        label: trimmed(raw.label || ucfirst(entityName))
      });
    }
    if (!normalized.length) {
      normalized.push({ name: "contacts", singular: "contact", label: "Contacts" });
      normalized.push({ name: "companies", singular: "company", label: "Companies" });
    }
    return normalized;
  }

  function scriptLiteral(value) {
    if (value === null || value === undefined) {
      return "''";
    }
    if (typeof value === "number" || typeof value === "boolean") {
      return String(value);
    }
    return JSON.stringify(String(value));
  }

  function compVariableNode(name, valueExpression, comment) {
    var node = {
      className: "ngx.components.UICompVariable#UICompVariable",
      name: name
    };
    var properties = {};
    if (comment) {
      properties.comment = String(comment);
    }
    properties.value = valueExpression || "''";
    node.properties = properties;
    return node;
  }

  function useVariableNode(name, valueExpression, comment) {
    var node = {
      className: "ngx.components.UIUseVariable#UIUseVariable",
      name: name,
      properties: {
        varValue: {
          mode: "SCRIPT",
          value: valueExpression || "''"
        }
      }
    };
    if (comment) {
      node.properties.comment = String(comment);
    }
    return node;
  }

  function plainTextNode(name, value) {
    return {
      className: "ngx.components.UIText#UIText",
      name: name,
      properties: {
        textValue: {
          mode: "PLAIN",
          value: value == null ? "" : String(value)
        }
      }
    };
  }

  function sharedSourceValue(projectName, priority, variableName) {
    return {
      mode: "SOURCE",
      value: JSON.stringify({
        filter: "Shared",
        project: projectName,
        input: "",
        model: {
          data: [{ priority: Number(priority), regular: true }],
          path: "?." + variableName,
          prefix: "",
          suffix: "",
          custom: "",
          useCustom: false
        }
      })
    };
  }

  function buildUseSharedNode(sharedQName, name, variables) {
    return {
      className: "ngx.components.UIUseShared#" + sharedQName,
      name: name,
      properties: {
        sharedcomponent: sharedQName
      },
      children: variables || []
    };
  }

  function dashboardStatCardTree(componentName) {
    return {
      className: "ngx.components.UISharedRegularComponent#UISharedRegularComponent",
      name: componentName,
      properties: {
        comment: "Deterministic CRUD dashboard stat card."
      },
      children: [
        compVariableNode("Title", "'Title'"),
        compVariableNode("Value", "'0'"),
        compVariableNode("Caption", "''"),
        {
          className: "ngx.components.UIDynamicElement#Card",
          name: "DashboardCard",
          children: [
            {
              className: "ngx.components.UIDynamicElement#CardHeader",
              name: "DashboardHeader",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#CardTitle",
                  name: "DashboardTitleSlot",
                  children: [plainTextNode("TitleText", "Title")]
                }
              ]
            },
            {
              className: "ngx.components.UIDynamicElement#CardContent",
              name: "DashboardContent",
              children: [
                plainTextNode("ValueText", "0"),
                plainTextNode("CaptionText", "")
              ]
            }
          ]
        }
      ]
    };
  }

  function stateComponentTree(componentName, comment, variableSpecs, shellName, lines, includeRetryButton) {
    var children = [];
    for (var i = 0; i < variableSpecs.length; i++) {
      children.push(compVariableNode(variableSpecs[i].name, variableSpecs[i].defaultValue, variableSpecs[i].comment));
    }
    var contentChildren = [];
    for (var line = 0; line < lines.length; line++) {
      contentChildren.push(plainTextNode(lines[line].nodeName, lines[line].defaultText));
    }
    if (includeRetryButton) {
      contentChildren.push({
        className: "ngx.components.UIDynamicElement#Button",
        name: "RetryButton",
        children: [plainTextNode("RetryText", "Retry")]
      });
    }
    children.push({
      className: "ngx.components.UIDynamicElement#Card",
      name: shellName,
      children: [
        {
          className: "ngx.components.UIDynamicElement#CardContent",
          name: shellName + "Content",
          children: contentChildren
        }
      ]
    });
    return {
      className: "ngx.components.UISharedRegularComponent#UISharedRegularComponent",
      name: componentName,
      properties: {
        comment: comment
      },
      children: children
    };
  }

  function entityTableTree(entity) {
    var componentName = ucfirst(entity.singular) + "Table";
    return {
      className: "ngx.components.UISharedRegularComponent#UISharedRegularComponent",
      name: componentName,
      properties: {
        comment: "Deterministic CRUD table summary for " + entity.label + "."
      },
      children: [
        compVariableNode("Title", scriptLiteral(entity.label)),
        compVariableNode("CountLabel", "'0 items'"),
        compVariableNode("Summary", "'Awaiting facade proof'"),
        compVariableNode("Source", "''"),
        {
          className: "ngx.components.UIDynamicElement#Card",
          name: componentName + "Card",
          children: [
            {
              className: "ngx.components.UIDynamicElement#CardHeader",
              name: componentName + "Header",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#CardTitle",
                  name: componentName + "TitleSlot",
                  children: [plainTextNode("TitleText", entity.label)]
                }
              ]
            },
            {
              className: "ngx.components.UIDynamicElement#CardContent",
              name: componentName + "Content",
              children: [
                plainTextNode("CountText", "0 items"),
                plainTextNode("SummaryText", "Awaiting facade proof"),
                plainTextNode("SourceText", "")
              ]
            }
          ]
        }
      ]
    };
  }

  function entityCardTree(entity) {
    var componentName = ucfirst(entity.singular) + "Card";
    return {
      className: "ngx.components.UISharedRegularComponent#UISharedRegularComponent",
      name: componentName,
      properties: {
        comment: "Deterministic CRUD entity card for " + entity.label + "."
      },
      children: [
        compVariableNode("Title", scriptLiteral(ucfirst(entity.singular))),
        compVariableNode("Primary", "'Primary field'"),
        compVariableNode("Secondary", "'Secondary field'"),
        {
          className: "ngx.components.UIDynamicElement#Card",
          name: componentName + "Root",
          children: [
            {
              className: "ngx.components.UIDynamicElement#CardHeader",
              name: componentName + "Header",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#CardTitle",
                  name: componentName + "TitleSlot",
                  children: [plainTextNode("TitleText", ucfirst(entity.singular))]
                }
              ]
            },
            {
              className: "ngx.components.UIDynamicElement#CardContent",
              name: componentName + "Content",
              children: [
                plainTextNode("PrimaryText", "Primary field"),
                plainTextNode("SecondaryText", "Secondary field")
              ]
            }
          ]
        }
      ]
    };
  }

  function entityFormTree(entity) {
    var componentName = ucfirst(entity.singular) + "Form";
    return {
      className: "ngx.components.UISharedRegularComponent#UISharedRegularComponent",
      name: componentName,
      properties: {
        comment: "Deterministic CRUD form shell for " + entity.label + "."
      },
      children: [
        compVariableNode("Title", scriptLiteral("Edit " + ucfirst(entity.singular))),
        compVariableNode("Helper", "'Fields will be wired in a second pass'"),
        compVariableNode("ActionLabel", "'Save'"),
        {
          className: "ngx.components.UIDynamicElement#Card",
          name: componentName + "Root",
          children: [
            {
              className: "ngx.components.UIDynamicElement#CardHeader",
              name: componentName + "Header",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#CardTitle",
                  name: componentName + "TitleSlot",
                  children: [plainTextNode("TitleText", "Edit " + ucfirst(entity.singular))]
                }
              ]
            },
            {
              className: "ngx.components.UIDynamicElement#CardContent",
              name: componentName + "Content",
              children: [
                plainTextNode("HelperText", "Fields will be wired in a second pass"),
                {
                  className: "ngx.components.UIDynamicElement#Button",
                  name: "SubmitButton",
                  children: [plainTextNode("ActionText", "Save")]
                }
              ]
            }
          ]
        }
      ]
    };
  }

  function buildSharedComponentsTree(projectName, entities) {
    var components = [
      dashboardStatCardTree("DashboardStatCard"),
      stateComponentTree(
        "CrudLoadingState",
        "Deterministic CRUD loading state.",
        [{ name: "Message", defaultValue: "'Loading data from public facade...'" }],
        "LoadingStateCard",
        [{ nodeName: "LoadingText", defaultText: "Loading data from public facade..." }],
        false
      ),
      stateComponentTree(
        "CrudEmptyState",
        "Deterministic CRUD empty state.",
        [{ name: "Message", defaultValue: "'No rows available yet.'" }],
        "EmptyStateCard",
        [{ nodeName: "EmptyText", defaultText: "No rows available yet." }],
        false
      ),
      stateComponentTree(
        "CrudErrorRetryState",
        "Deterministic CRUD error and retry state.",
        [
          { name: "Message", defaultValue: "'Retry to reload the public facade.'" },
          { name: "ButtonLabel", defaultValue: "'Retry'" }
        ],
        "ErrorStateCard",
        [{ nodeName: "ErrorText", defaultText: "Retry to reload the public facade." }],
        true
      )
    ];
    for (var i = 0; i < entities.length; i++) {
      components.push(entityTableTree(entities[i]));
      components.push(entityCardTree(entities[i]));
      components.push(entityFormTree(entities[i]));
    }
    return {
      qnames: components.map(function (component) { return sharedComponentQName(projectName, component.name); }),
      tree: {
        children: components
      }
    };
  }

  function buildPageShellTree(projectName, entryPage, entities, evidence) {
    var contactEntity = entities[0];
    var companyEntity = entities[Math.min(1, entities.length - 1)];
    var contactCount = evidence && evidence.count_contacts && evidence.count_contacts.total != null ? evidence.count_contacts.total : "Loading...";
    var companyCount = evidence && evidence.count_companies && evidence.count_companies.total != null ? evidence.count_companies.total : "Loading...";
    var contactSummary = evidence && evidence.list_contacts && evidence.list_contacts.itemCount != null
      ? evidence.list_contacts.itemCount + " contact rows proved"
      : "Waiting for contact rows";
    var companySummary = evidence && evidence.list_companies && evidence.list_companies.itemCount != null
      ? evidence.list_companies.itemCount + " company rows proved"
      : "Waiting for company rows";
    return {
      className: "ngx.components.UIDynamicElement#Content",
      name: "Content",
      children: [
        {
          className: "ngx.components.UIDynamicElement#Grid",
          name: "CrudDashboardGrid",
          children: [
            {
              className: "ngx.components.UIDynamicElement#GridRow",
              name: "HeaderRow",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#GridCol",
                  name: "HeaderCol",
                  children: [
                    plainTextNode("DashboardTitle", ucfirst(projectName) + " Live Dashboard"),
                    plainTextNode("DashboardSubtitle", entities.map(function (entity) { return entity.label.toLowerCase(); }).join(" and "))
                  ]
                }
              ]
            },
            {
              className: "ngx.components.UIDynamicElement#GridRow",
              name: "MetricsRow",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#GridCol",
                  name: "ContactsStatCol",
                  children: [
                    buildUseSharedNode(sharedComponentQName(projectName, "DashboardStatCard"), "UseContactsStatCard", [
                      useVariableNode("Title", scriptLiteral(contactEntity.label)),
                      useVariableNode("Value", scriptLiteral(String(contactCount))),
                      useVariableNode("Caption", scriptLiteral("Loaded from public facade"))
                    ])
                  ]
                },
                {
                  className: "ngx.components.UIDynamicElement#GridCol",
                  name: "CompaniesStatCol",
                  children: [
                    buildUseSharedNode(sharedComponentQName(projectName, "DashboardStatCard"), "UseCompaniesStatCard", [
                      useVariableNode("Title", scriptLiteral(companyEntity.label)),
                      useVariableNode("Value", scriptLiteral(String(companyCount))),
                      useVariableNode("Caption", scriptLiteral("Loaded from public facade"))
                    ])
                  ]
                }
              ]
            },
            {
              className: "ngx.components.UIDynamicElement#GridRow",
              name: "EntityTablesRow",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#GridCol",
                  name: "ContactsTableCol",
                  children: [
                    buildUseSharedNode(sharedComponentQName(projectName, ucfirst(contactEntity.singular) + "Table"), "Use" + ucfirst(contactEntity.singular) + "Table", [
                      useVariableNode("Title", scriptLiteral(contactEntity.label)),
                      useVariableNode("CountLabel", scriptLiteral(String(contactCount) + " rows")),
                      useVariableNode("Summary", scriptLiteral(contactSummary)),
                      useVariableNode("Source", scriptLiteral("Facade " + projectName + ".crm_list_contacts"))
                    ])
                  ]
                },
                {
                  className: "ngx.components.UIDynamicElement#GridCol",
                  name: "CompaniesTableCol",
                  children: [
                    buildUseSharedNode(sharedComponentQName(projectName, ucfirst(companyEntity.singular) + "Table"), "Use" + ucfirst(companyEntity.singular) + "Table", [
                      useVariableNode("Title", scriptLiteral(companyEntity.label)),
                      useVariableNode("CountLabel", scriptLiteral(String(companyCount) + " rows")),
                      useVariableNode("Summary", scriptLiteral(companySummary)),
                      useVariableNode("Source", scriptLiteral("Facade " + projectName + ".crm_list_companies"))
                    ])
                  ]
                }
              ]
            },
            {
              className: "ngx.components.UIDynamicElement#GridRow",
              name: "StatesRow",
              children: [
                {
                  className: "ngx.components.UIDynamicElement#GridCol",
                  name: "LoadingCol",
                  children: [
                    buildUseSharedNode(sharedComponentQName(projectName, "CrudLoadingState"), "UseCrudLoadingState", [
                      useVariableNode("Message", scriptLiteral("Loading data from public facade..."))
                    ])
                  ]
                },
                {
                  className: "ngx.components.UIDynamicElement#GridCol",
                  name: "ErrorRetryCol",
                  children: [
                    buildUseSharedNode(sharedComponentQName(projectName, "CrudErrorRetryState"), "UseCrudErrorRetryState", [
                      useVariableNode("Message", scriptLiteral("Retry if one facade call fails.")),
                      useVariableNode("ButtonLabel", scriptLiteral("Retry"))
                    ])
                  ]
                }
              ]
            }
          ]
        }
      ]
    };
  }

  function patchTextBinding(targetQName, sourceValue, result) {
    try {
      var targetDbo = C8O.dbo.resolve(targetQName, { optional: true });
      if (!targetDbo) {
        addWarning(result, "Shared text binding target missing: " + targetQName);
        return;
      }
      applyUpdates(targetDbo, { textValue: sourceValue }, result);
    } catch (patchError) {
      addWarning(result, "Unable to patch shared text binding for " + targetQName + ": " + String(patchError));
    }
  }

  function configureSharedBindings(projectName, entities, result) {
    var componentBindings = [
      {
        componentName: "DashboardStatCard",
        bindings: [
          { suffix: ".DashboardCard.DashboardHeader.DashboardTitleSlot.TitleText", variableName: "Title" },
          { suffix: ".DashboardCard.DashboardContent.ValueText", variableName: "Value" },
          { suffix: ".DashboardCard.DashboardContent.CaptionText", variableName: "Caption" }
        ]
      },
      {
        componentName: "CrudLoadingState",
        bindings: [
          { suffix: ".LoadingStateCard.LoadingStateCardContent.LoadingText", variableName: "Message" }
        ]
      },
      {
        componentName: "CrudEmptyState",
        bindings: [
          { suffix: ".EmptyStateCard.EmptyStateCardContent.EmptyText", variableName: "Message" }
        ]
      },
      {
        componentName: "CrudErrorRetryState",
        bindings: [
          { suffix: ".ErrorStateCard.ErrorStateCardContent.ErrorText", variableName: "Message" },
          { suffix: ".ErrorStateCard.ErrorStateCardContent.RetryButton.RetryText", variableName: "ButtonLabel" }
        ]
      }
    ];

    for (var i = 0; i < entities.length; i++) {
      var componentPrefix = ucfirst(entities[i].singular);
      componentBindings.push({
        componentName: componentPrefix + "Table",
        bindings: [
          { suffix: "." + componentPrefix + "TableCard." + componentPrefix + "TableHeader." + componentPrefix + "TableTitleSlot.TitleText", variableName: "Title" },
          { suffix: "." + componentPrefix + "TableCard." + componentPrefix + "TableContent.CountText", variableName: "CountLabel" },
          { suffix: "." + componentPrefix + "TableCard." + componentPrefix + "TableContent.SummaryText", variableName: "Summary" },
          { suffix: "." + componentPrefix + "TableCard." + componentPrefix + "TableContent.SourceText", variableName: "Source" }
        ]
      });
      componentBindings.push({
        componentName: componentPrefix + "Card",
        bindings: [
          { suffix: "." + componentPrefix + "CardRoot." + componentPrefix + "CardHeader." + componentPrefix + "CardTitleSlot.TitleText", variableName: "Title" },
          { suffix: "." + componentPrefix + "CardRoot." + componentPrefix + "CardContent.PrimaryText", variableName: "Primary" },
          { suffix: "." + componentPrefix + "CardRoot." + componentPrefix + "CardContent.SecondaryText", variableName: "Secondary" }
        ]
      });
      componentBindings.push({
        componentName: componentPrefix + "Form",
        bindings: [
          { suffix: "." + componentPrefix + "FormRoot." + componentPrefix + "FormHeader." + componentPrefix + "FormTitleSlot.TitleText", variableName: "Title" },
          { suffix: "." + componentPrefix + "FormRoot." + componentPrefix + "FormContent.HelperText", variableName: "Helper" },
          { suffix: "." + componentPrefix + "FormRoot." + componentPrefix + "FormContent.SubmitButton.ActionText", variableName: "ActionLabel" }
        ]
      });
    }

    for (var bindingIndex = 0; bindingIndex < componentBindings.length; bindingIndex++) {
      var componentQName = sharedComponentQName(projectName, componentBindings[bindingIndex].componentName);
      var componentDbo = C8O.dbo.resolve(componentQName, { optional: true });
      if (!componentDbo) {
        addWarning(result, "Shared component missing after apply: " + componentQName);
        continue;
      }
      var componentPriority = priorityOf(componentDbo);
      for (var bindingEntry = 0; bindingEntry < componentBindings[bindingIndex].bindings.length; bindingEntry++) {
        var binding = componentBindings[bindingIndex].bindings[bindingEntry];
        patchTextBinding(componentQName + binding.suffix, sharedSourceValue(projectName, componentPriority, binding.variableName), result);
      }
    }
  }

  function auditUiTreePayload(uiTree) {
    var serialized = JSON.stringify(uiTree || {});
    return {
      starterDominant: serialized.indexOf("WelcomeCard") !== -1,
      visibleShellPresent: /FeatureShell|CrudDashboardGrid|DashboardTitle|UseContactsStatCard|UseCompaniesStatCard|UseCrudLoadingState|UseCrudErrorRetryState/.test(serialized),
      liveBindingPresent: /UIDynamicAction|UIDynamicInvoke|UIActionStack|UIControlDirective|UIControlVariable|UIUseShared/.test(serialized)
    };
  }

  function collectSharedRefs(node, refs) {
    refs = refs || [];
    if (!node || typeof node !== "object") {
      return refs;
    }
    if (node.properties && node.properties.sharedcomponent) {
      refs.push(String(node.properties.sharedcomponent));
    }
    var children = ensureArray(node.children);
    for (var i = 0; i < children.length; i++) {
      collectSharedRefs(children[i], refs);
    }
    return refs;
  }

  function upsertNgxCrudKit(options) {
    var result = {
      status: "success",
      project: "",
      sharedComponents: [],
      pageTargets: [],
      runtimeEvidence: {},
      warnings: [],
      created: [],
      updated: []
    };
    var projectName = trimmed(options.project);
    if (!projectName.length) {
      throw new Error("project is required");
    }
    result.project = projectName;
    var project = findProjectByName(projectName);
    if (!project) {
      throw new Error("Project " + projectName + " is not loaded");
    }
    var entities = normalizeUiEntities(options.entities);
    var entryPage = trimmed(options.entryPage || "Page");
    var facadePrefix = trimmed(options.facadePrefix || "crud");
    var contentQName = findPageContentQName(projectName, entryPage);
    var ngxApp = C8O.dbo.resolve(ngxAppQName(projectName), { optional: true });
    var contentDbo = C8O.dbo.resolve(contentQName, { optional: true });
    if (!ngxApp) {
      throw new Error("NGX application root not found for " + projectName);
    }
    if (!contentDbo) {
      throw new Error("Entry page content not found for " + projectName + ": " + contentQName);
    }
    var sharedComponents = buildSharedComponentsTree(projectName, entities);
    var beforeCreated = result.created.length;
    for (var sharedIndex = 0; sharedIndex < ensureArray(sharedComponents.tree.children).length; sharedIndex++) {
      syncDeterministicNode(ngxApp, sharedComponents.tree.children[sharedIndex], result, true);
    }
    result.sharedComponents = sharedComponents.qnames.slice();
    result.runtimeEvidence.sharedComponentsApply = {
      status: result.created.length > beforeCreated ? "success" : "updated",
      target: ngxAppQName(projectName)
    };
    configureSharedBindings(projectName, entities, result);
    var pageShellTree = buildPageShellTree(projectName, entryPage, entities, options.runtimeEvidence || {});
    if (pageShellTree.properties) {
      applyUpdates(contentDbo, pageShellTree.properties, result);
    }
    var desiredChildren = ensureArray(pageShellTree.children);
    var desiredNames = {};
    for (var childIndex = 0; childIndex < desiredChildren.length; childIndex++) {
      if (desiredChildren[childIndex] && desiredChildren[childIndex].name) {
        desiredNames[String(desiredChildren[childIndex].name)] = true;
      }
    }
    var contentChildren = getChildrenArray(contentDbo);
    for (var existingIndex = 0; existingIndex < contentChildren.length; existingIndex++) {
      var existingChild = contentChildren[existingIndex];
      var existingName = "";
      try {
        existingName = String(existingChild.getName());
      } catch (_ignoreExistingName) {
        existingName = "";
      }
      if (existingName && !desiredNames[existingName]) {
        removeChild(contentDbo, existingChild, result);
      }
    }
    for (var pageChildIndex = 0; pageChildIndex < desiredChildren.length; pageChildIndex++) {
      syncDeterministicNode(contentDbo, desiredChildren[pageChildIndex], result, true);
    }
    result.pageTargets.push(contentQName);
    result.runtimeEvidence.treeApply = {
      status: "success",
      target: contentQName
    };
    result.runtimeEvidence.entryPage = entryPage;
    result.runtimeEvidence.facadePrefix = facadePrefix;
    result.runtimeEvidence.pageSharedRefs = collectSharedRefs(pageShellTree, []);
    try {
      var uiTree = callInternalSequence("tools_databaseobject_tree_get", {
        target: contentQName,
        childrenDepth: 2,
        properties: "none",
        limit: 120
      });
      var uiAudit = auditUiTreePayload(uiTree);
      result.runtimeEvidence.shellVisible = uiAudit.visibleShellPresent;
      result.runtimeEvidence.starterDominant = uiAudit.starterDominant;
      result.runtimeEvidence.liveBindingPresent = uiAudit.liveBindingPresent;
    } catch (uiInspectError) {
      result.status = "partial";
      addWarning(result, "Unable to inspect NGX shell after apply: " + String(uiInspectError));
    }
    try {
      result.runtimeEvidence.projectSave = summarizeSaveResult(C8O.dbo.saveProject(project, []), result);
      result.runtimeEvidence.studioRefresh = refreshStudioProjectTree(project, result, "studioRefresh");
    } catch (saveUiError) {
      result.status = "partial";
      addWarning(result, "Unable to save project after NGX CRUD kit apply: " + String(saveUiError));
    }
    delete result.created;
    delete result.updated;
    return result;
  }

  function buildCrudStatus(spec, connector, result) {
    var project = findProjectByName(spec.project);
    var status = {
      status: "ok",
      project: spec.project,
      driverFamily: spec.database.driver.id,
      connectorQname: connector && connector.getFullQName ? String(connector.getFullQName()) : "",
      transactions: {
        present: [],
        missing: []
      },
      sequences: {
        present: [],
        missing: []
      },
      ui: {
        starterDominant: null,
        visibleShellPresent: false,
        liveBindingPresent: false,
        targetQName: findPageContentQName(spec.project, spec.ui.entryPage)
      },
      missing: [],
      warnings: []
    };

    var expectedTransactions = ["init_schema"];
    for (var i = 0; i < spec.entities.length; i++) {
      expectedTransactions.push(txName(spec.entities[i], "list"));
      expectedTransactions.push(txName(spec.entities[i], "count"));
      expectedTransactions.push(txName(spec.entities[i], "read"));
      expectedTransactions.push(txName(spec.entities[i], "create"));
      expectedTransactions.push(txName(spec.entities[i], "update"));
      expectedTransactions.push(txName(spec.entities[i], "delete"));
    }
    if (!spec.entities.length && connector && connector.getTransactionsList) {
      try {
        var txList = connector.getTransactionsList();
        for (var txIndex = 0; txIndex < txList.size(); txIndex++) {
          var txNameValue = trimmed(txList.get(txIndex).getName());
          if (txNameValue.length && expectedTransactions.indexOf(txNameValue) === -1) {
            expectedTransactions.push(txNameValue);
          }
        }
      } catch (_ignoreTxList) {}
    }

    for (var j = 0; j < expectedTransactions.length; j++) {
      var txQName = spec.project + "." + spec.database.connector + "." + expectedTransactions[j];
      if (C8O.dbo.resolve(txQName, { optional: true })) {
        status.transactions.present.push(txQName);
      } else {
        status.transactions.missing.push(txQName);
        status.missing.push(txQName);
      }
    }

    if (toBoolean(result.sequence, true)) {
      for (var k = 0; k < spec.entities.length; k++) {
        var entity = spec.entities[k];
        var verbs = ["list", "count", "read", "create", "update", "delete"];
        for (var v = 0; v < verbs.length; v++) {
          var seqName = spec.facade.prefix + "_" + txName(entity, verbs[v]);
          var seqQName = spec.project + "." + seqName;
          if (C8O.dbo.resolve(seqQName, { optional: true })) {
            status.sequences.present.push(seqQName);
          } else {
            status.sequences.missing.push(seqQName);
            status.missing.push(seqQName);
          }
        }
      }
      if (!spec.entities.length && project && project.getSequencesList) {
        try {
          var sequences = project.getSequencesList();
          var sequencePrefix = spec.project + ".sq:" + spec.facade.prefix + "_";
          for (var seqIndex = 0; seqIndex < sequences.size(); seqIndex++) {
            var sequence = sequences.get(seqIndex);
            var seqQNameAny = sequence.getFullQName ? String(sequence.getFullQName()) : "";
            if (seqQNameAny.indexOf(sequencePrefix) === 0) {
              status.sequences.present.push(seqQNameAny);
            }
          }
        } catch (_ignoreSequencesList) {}
      }
    }

    try {
      var uiTree = callInternalSequence("tools_databaseobject_tree_get", {
        target: status.ui.targetQName,
        childrenDepth: 2,
        properties: "none",
        limit: 120
      });
      var uiAudit = auditUiTreePayload(uiTree);
      status.ui.starterDominant = uiAudit.starterDominant;
      status.ui.visibleShellPresent = uiAudit.visibleShellPresent;
      status.ui.liveBindingPresent = uiAudit.liveBindingPresent;
    } catch (uiError) {
      addWarning(status, "Unable to inspect UI target: " + String(uiError));
    }

    if (status.missing.length) {
      status.status = "partial";
    }
    return status;
  }

  function upsertCrud(options) {
    var result = {
      status: "success",
      project: "",
      driverFamily: "",
      connectorQname: "",
      primaryTargets: {
        sql: "",
        flow: [],
        ui: []
      },
      created: [],
      updated: [],
      runtimeEvidence: {},
      warnings: [],
      sequence: toBoolean(options.sequence, true),
      uiEnabled: toBoolean(options.ui, false)
    };

    var spec = normalizeSpec(options.spec);
    result.project = spec.project;
    result.driverFamily = spec.database.driver.id;
    var project = ensureProject(spec, result);
    var connector = ensureConnector(project, spec, result);
    result.connectorQname = connector.getFullQName ? String(connector.getFullQName()) : (spec.project + "." + spec.database.connector);
    result.primaryTargets.sql = result.connectorQname;

    ensureSqlTransaction(connector, "BeginTransaction", "BEGIN;", SqlTransaction.AUTOCOMMIT_OFF, result);
    ensureSqlTransaction(connector, "CommitTransaction", "COMMIT;", SqlTransaction.AUTOCOMMIT_OFF, result);
    ensureSqlTransaction(connector, "RollbackTransaction", "ROLLBACK;", SqlTransaction.AUTOCOMMIT_OFF, result);
    ensureSqlTransaction(connector, "init_schema", buildInitSql(spec), SqlTransaction.AUTOCOMMIT_OFF, result);

    for (var i = 0; i < spec.entities.length; i++) {
      var entity = spec.entities[i];
      var listTx = ensureSqlTransaction(connector, txName(entity, "list"), buildCrudSql(entity, "list"), SqlTransaction.AUTOCOMMIT_EACH, result);
      var countTx = ensureSqlTransaction(connector, txName(entity, "count"), buildCrudSql(entity, "count"), SqlTransaction.AUTOCOMMIT_EACH, result);
      var readTx = ensureSqlTransaction(connector, txName(entity, "read"), buildCrudSql(entity, "read"), SqlTransaction.AUTOCOMMIT_EACH, result);
      var createTx = ensureSqlTransaction(connector, txName(entity, "create"), buildCrudSql(entity, "create"), SqlTransaction.AUTOCOMMIT_EACH, result);
      var updateTx = ensureSqlTransaction(connector, txName(entity, "update"), buildCrudSql(entity, "update"), SqlTransaction.AUTOCOMMIT_EACH, result);
      var deleteTx = ensureSqlTransaction(connector, txName(entity, "delete"), buildCrudSql(entity, "delete"), SqlTransaction.AUTOCOMMIT_EACH, result);

      if (result.sequence) {
        var listVars = collectTransactionVariables(listTx);
        var countVars = collectTransactionVariables(countTx);
        var readVars = collectTransactionVariables(readTx);
        var createVars = collectTransactionVariables(createTx);
        var updateVars = collectTransactionVariables(updateTx);
        var deleteVars = collectTransactionVariables(deleteTx);
        var publicNames = [
          spec.facade.prefix + "_" + txName(entity, "list"),
          spec.facade.prefix + "_" + txName(entity, "count"),
          spec.facade.prefix + "_" + txName(entity, "read"),
          spec.facade.prefix + "_" + txName(entity, "create"),
          spec.facade.prefix + "_" + txName(entity, "update"),
          spec.facade.prefix + "_" + txName(entity, "delete")
        ];
        var publicSources = [
          result.connectorQname + "." + txName(entity, "list"),
          result.connectorQname + "." + txName(entity, "count"),
          result.connectorQname + "." + txName(entity, "read"),
          result.connectorQname + "." + txName(entity, "create"),
          result.connectorQname + "." + txName(entity, "update"),
          result.connectorQname + "." + txName(entity, "delete")
        ];
        var publicVars = [listVars, countVars, readVars, createVars, updateVars, deleteVars];
        for (var p = 0; p < publicNames.length; p++) {
          var seq = ensurePublicSequence(project, publicNames[p], publicSources[p], publicVars[p], result);
          result.primaryTargets.flow.push(seq.getFullQName ? String(seq.getFullQName()) : (spec.project + "." + publicNames[p]));
        }
      }
    }

    var saveResult = C8O.dbo.saveProject(project, []);
    result.runtimeEvidence.projectSave = summarizeSaveResult(saveResult, result);
    result.runtimeEvidence.studioRefresh = refreshStudioProjectTree(project, result, "studioRefresh");
    result.runtimeEvidence.init_schema = proofRequestable(spec.project + "." + spec.database.connector + ".init_schema", {}, result);
    for (var e = 0; e < spec.entities.length; e++) {
      var currentEntity = spec.entities[e];
      result.runtimeEvidence[txName(currentEntity, "list")] = proofRequestable(spec.project + "." + spec.database.connector + "." + txName(currentEntity, "list"), {}, result);
      result.runtimeEvidence[txName(currentEntity, "count")] = proofRequestable(spec.project + "." + spec.database.connector + "." + txName(currentEntity, "count"), {}, result);
    }

    if (result.uiEnabled) {
      var uiResult = upsertNgxCrudKit({
        project: spec.project,
        entities: spec.entities,
        variant: spec.ui.variant,
        facadePrefix: spec.facade.prefix,
        entryPage: spec.ui.entryPage,
        runtimeEvidence: result.runtimeEvidence
      });
      result.runtimeEvidence.ui = {
        status: uiResult.status,
        pageTargets: uiResult.pageTargets || [],
        shellVisible: uiResult.runtimeEvidence ? uiResult.runtimeEvidence.shellVisible === true : false,
        starterDominant: uiResult.runtimeEvidence ? uiResult.runtimeEvidence.starterDominant === true : null
      };
      result.primaryTargets.ui = uiResult.pageTargets || [];
      if (uiResult.status !== "success") {
        result.status = "partial";
      }
      if (uiResult.runtimeEvidence && uiResult.runtimeEvidence.projectSave) {
        result.runtimeEvidence.uiProjectSave = uiResult.runtimeEvidence.projectSave;
      }
      if (uiResult.warnings && uiResult.warnings.length) {
        for (var w = 0; w < uiResult.warnings.length; w++) {
          addWarning(result, uiResult.warnings[w]);
        }
      }
    }

    result.status = result.warnings.length ? "partial" : "success";
    return C8O.util.toJsonSafe ? C8O.util.toJsonSafe(result, { warnings: ensureWarnings(result), path: "$" }) : result;
  }

  function crudStatus(options) {
    var projectName = trimmed(options.project);
    if (!projectName.length) {
      throw new Error("project is required");
    }
    var project = findProjectByName(projectName);
    if (!project) {
      return {
        status: "not_found",
        project: projectName,
        connectorQname: "",
        driverFamily: "",
        missing: [projectName],
        warnings: []
      };
    }
    var fakeSpec = {
      project: projectName,
      starter: "ngx",
      facade: {
        prefix: trimmed(options.facadePrefix || "crud"),
        publicListSequence: ""
      },
      seed: { enabled: true, rowsPerEntity: 2 },
      ui: { entryPage: "Page", variant: trimmed(options.variant || "dashboard") },
      database: normalizeDatabaseSpec({
        project: projectName,
        database: {
          mode: options.mode || "hsqldb",
          connector: options.connector || "appdb"
        }
      }, {}),
      entities: []
    };
    var connectorName = trimmed(options.connector || "");
    var connector = findSqlConnectorInProject(project, connectorName);
    if (!connectorName.length && connector && connector.getName) {
      connectorName = String(connector.getName());
    }
    if (!connector && !connectorName.length) {
      connectorName = fakeSpec.database.connector;
    }
    var status = buildCrudStatus(fakeSpec, connector, {
      sequence: true,
      warnings: []
    });
    if (!connector) {
      status.status = "partial";
      status.missing.push(projectName + "." + connectorName);
    } else {
      status.driverFamily = inferDriverFamilyFromConnector(connector);
    }
    return C8O.util.toJsonSafe ? C8O.util.toJsonSafe(status, { warnings: ensureWarnings(status), path: "$" }) : status;
  }

  C8O.crud.normalizeSpec = normalizeSpec;
  C8O.crud.upsertCrud = function (options) {
    return upsertCrud(options || {});
  };
  C8O.crud.crudStatus = function (options) {
    return crudStatus(options || {});
  };
  C8O.crud.upsertNgxCrudKit = function (options) {
    var result = upsertNgxCrudKit(options || {});
    return C8O.util.toJsonSafe ? C8O.util.toJsonSafe(result, { warnings: ensureWarnings(result), path: "$" }) : result;
  };
})();
